import Foundation
import Testing
@testable import GraithSessionKit

// Capability manifest ↔ shared-layer conformance (issue #1149).
//
// `internal/capabilities/capabilities.json` is the hand-maintained source of
// truth for which capabilities each frontend surfaces. The Go side already
// guards doc ↔ manifest (`TestDocMatchesManifest`); this is the missing
// manifest ↔ code guard, mirroring the #1144 protocol approach:
//
//   - Go projects the manifest to a language-neutral fixture
//     (`Fixtures/capability_manifest.json`, generated by
//     `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`)
//     carrying each capability's iOS + macOS state.
//   - This test decodes that fixture and cross-checks it against
//     `sharedAffordances()` — the set of capabilities the shared
//     `GraithSessionKit` layer wires. Since #1147 both apps bind to that one
//     layer (`FleetModel` / `HostConnection` / `TerminalAttachViewModel` / the
//     `GraithHostClient` boundary), so a capability wired there is *available*
//     to both GUIs.
//
// The registry is *compile-anchored*: each entry references the real shared
// symbol behind it, so renaming or deleting the wiring stops this file from
// compiling — a registered row can't outlive its code.
//
// SCOPE — what this proves, and what it does not (deliberately narrow, cf. the
// #1149 review):
//
//   - Guaranteed: the manifest cannot over- or under-claim relative to the
//     *shared* capability surface. A capability the manifest marks `supported`
//     on a GUI must have a backing shared affordance (or a declared view-only
//     exception); a wired affordance the manifest marks anything but
//     `supported` is a red test on every targeted GUI surface; iOS/macOS must
//     stay at parity when both are targeted. A registered row is rot-proof
//     against renames/removals via the compile anchor.
//   - NOT guaranteed: that each app's *views* actually surface the capability.
//     The shared layer is the model surface, not the SwiftUI/AppKit views the
//     apps own on top of it — and surfacing is sometimes a semantic judgment
//     (e.g. iOS surfaces `terminal.logs` / `terminal.screen-snapshot` through
//     the live attach view rather than a dedicated sheet). Per-app view
//     surfacing therefore stays a *reviewed* decision, tracked by the checklist
//     documented in AGENTS.md — a naive view-type anchor would false-positive
//     on the covered-by-attach cases. An automated per-app view-anchor guard is
//     a follow-up, not part of this pass.
//   - Also manual: adding a *new* shared affordance requires adding its row
//     here. The anchor keeps an existing row honest; it cannot discover wiring
//     that was never registered. This is the same discipline as the manifest it
//     guards, now with a compile tripwire on the registered set.

// MARK: - Fixture DTOs

private struct CapabilityFixture: Decodable {
    let version: Int
    let capabilities: [CapabilityEntry]
}

private struct CapabilityEntry: Decodable {
    let id: String
    let ios: String
    let macos: String
    let platformDecision: String?

    private enum CodingKeys: String, CodingKey {
        case id, ios, macos
        case platformDecision = "platform_decision"
    }
}

private enum CapabilityFixtureError: Error, CustomStringConvertible {
    case missing
    var description: String {
        "capability_manifest.json not found in the test bundle — check the resources: entry in Package.swift, and regenerate with `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`"
    }
}

private func loadCapabilityManifest() throws -> CapabilityFixture {
    let candidates: [(String, String?)] = [
        ("capability_manifest", "Fixtures"),
        ("capability_manifest", nil),
    ]
    for (resource, subdir) in candidates {
        if let url = Bundle.module.url(forResource: resource, withExtension: "json", subdirectory: subdir) {
            return try JSONDecoder().decode(CapabilityFixture.self, from: try Data(contentsOf: url))
        }
    }
    throw CapabilityFixtureError.missing
}

// MARK: - The shared-layer affordance registry (compile-anchored)

/// The capabilities the shared `GraithSessionKit` layer wires. Each `wire`
/// entry touches the real symbol behind the capability, so a rename/removal is
/// a compile error here — the registry cannot claim a capability the code no
/// longer provides. Returns the set of capability ids for the checks below.
@MainActor
private func sharedAffordances() -> Set<String> {
    var ids: Set<String> = []
    func wire(_ id: String, _ anchor: () -> Void) {
        anchor()
        ids.insert(id)
    }

    // Session lifecycle — FleetModel routes every action to the owning host.
    wire("session.list") { _ = \FleetModel.sessions }
    // Sidebar filter/search/view-mode (#906) — shared filter state + pure logic.
    wire("session.filter") { _ = FleetModel.filtered }
    wire("session.create") { _ = FleetModel.createSession }
    wire("session.stop") { _ = FleetModel.stopSession }
    wire("session.resume") { _ = FleetModel.resumeSession }
    wire("session.restart") { _ = FleetModel.restartSession }
    wire("session.delete") { _ = FleetModel.deleteSession }
    wire("session.restore") { _ = FleetModel.restore }
    wire("session.purge") { _ = FleetModel.purge }
    wire("session.rename") { _ = FleetModel.renameSession }
    wire("session.star") { _ = FleetModel.toggleStar }
    wire("session.fork") { _ = FleetModel.forkSession }
    wire("session.migrate") { _ = FleetModel.migrateSession }
    wire("session.set-status") { _ = FleetModel.setStatus }
    wire("session.repo-list") { _ = HostConnection.repoList }

    // Document store browser (#902) — shared HostConnection reads.
    wire("store.browse") {
        _ = HostConnection.storeList
        _ = HostConnection.storeGet
    }

    // Terminal I/O — the shared attach view-model drives attach/input/resize/detach.
    wire("terminal.attach") { _ = TerminalAttachViewModel.attach }
    wire("terminal.input") { _ = TerminalAttachViewModel.sendRaw }
    wire("terminal.resize") { _ = TerminalAttachViewModel.resize }
    wire("terminal.detach") { _ = TerminalAttachViewModel.detach }
    // logs + screen-snapshot are boundary reads (GraithHostClient); anchor to
    // their wire control-type constants, which exist iff the boundary defines them.
    wire("terminal.logs") { _ = ControlType.logs }
    wire("terminal.screen-snapshot") { _ = ControlType.screenSnapshot }

    // Messaging — FleetModel routes send/read/ack to the owning host.
    wire("messaging.send") { _ = FleetModel.sendMessage }
    wire("messaging.read") { _ = FleetModel.conversation }

    // Pairing.
    wire("pairing.request") { _ = ControlType.pairRequest }

    // Host introspection — config viewer + diagnostics panel (#904). FleetModel
    // fetches both over the control protocol; the shared HealthReport derives
    // the doctor-style findings both apps render.
    wire("config.view") { _ = FleetModel.config }
    wire("doctor.diagnostics") { _ = FleetModel.diagnostics; _ = HealthReport.findings }

    return ids
}

/// Capabilities the manifest may mark `supported` on a GUI without a shared
/// affordance — genuinely per-app view wiring that can't be reflected from the
/// shared layer. Empty today: every GUI-supported capability is shared-routed.
/// Adding an id here is the "explicit, reviewed exception" the issue calls for,
/// not a silent hand-edit.
private let viewOnlyCapabilities: Set<String> = []

// MARK: - Tests

struct CapabilityConformanceTests {
    /// The core manifest ↔ code guard. A wired shared affordance must be
    /// `supported` on both GUIs, and a GUI-`supported` capability must have a
    /// backing affordance (or a declared view-only exception).
    @MainActor @Test func manifestMatchesSharedAffordances() throws {
        let manifest = try loadCapabilityManifest()
        let byID = Dictionary(uniqueKeysWithValues: manifest.capabilities.map { ($0.id, $0) })
        let shared = sharedAffordances()

        // Reverse-lie: everything the shared layer wires must be a manifest id
        // and `supported` on every targeted GUI — the #1143 direction (code
        // ahead of the manifest) as a red test, for the capabilities registered
        // here. Shared model availability does not pull an intentionally
        // excluded app surface back into product scope.
        for id in shared.sorted() {
            guard let c = byID[id] else {
                Issue.record("shared affordance `\(id)` is not a capability in the manifest — fix the id in sharedAffordances() or add it to capabilities.json")
                continue
            }
            if c.ios != "n/a" {
                #expect(
                    c.ios == "supported",
                    "`\(id)` is wired in GraithSessionKit but the targeted iOS surface is `\(c.ios)` — update capabilities.json + regenerate"
                )
            }
            if c.macos != "n/a" {
                #expect(
                    c.macos == "supported",
                    "`\(id)` is wired in GraithSessionKit but the targeted macOS surface is `\(c.macos)` — update capabilities.json + regenerate"
                )
            }
        }

        // Forward-lie: a GUI-`supported` capability must be backed by a shared
        // affordance, or explicitly declared view-only.
        for c in manifest.capabilities where c.ios == "supported" || c.macos == "supported" {
            #expect(
                shared.contains(c.id) || viewOnlyCapabilities.contains(c.id),
                "`\(c.id)` is `supported` on a GUI but nothing declares it: wire it in sharedAffordances() (with a compile anchor) or add it to viewOnlyCapabilities with a reason"
            )
        }
    }

    /// View-level scope + parity guard. Targeted GUI surfaces remain
    /// parity-by-construction. An `n/a` surface is outside that comparison, but
    /// must carry the design-doc decision that deliberately excluded it.
    @Test func guiParityHolds() throws {
        let manifest = try loadCapabilityManifest()
        for c in manifest.capabilities {
            let iosTargeted = c.ios != "n/a"
            let macOSTargeted = c.macos != "n/a"

            if !iosTargeted || !macOSTargeted {
                #expect(
                    !(c.platformDecision ?? "").isEmpty,
                    "capability `\(c.id)` excludes a GUI surface but has no platform_decision — link the feature design's ## Platform support section"
                )
            }

            if iosTargeted && macOSTargeted {
                #expect(
                    c.ios == c.macos,
                    "capability `\(c.id)` targets both GUIs but diverges (iOS=\(c.ios), macOS=\(c.macos)) — targeted surfaces must stay at parity"
                )
            }
        }
    }

    /// Sanity: the fixture loads and carries the manifest version the check
    /// speaks, so a future manifest-version bump is noticed here too.
    @Test func fixtureLoads() throws {
        let manifest = try loadCapabilityManifest()
        #expect(!manifest.capabilities.isEmpty)
        #expect(manifest.version == 2, "capability fixture version \(manifest.version) — the conformance check models version 2")
    }

    /// Guards against a stale view-only exception outliving its need. Platform
    /// scope is manifest-owned; this remaining implementation exception must be
    /// a real GUI-supported capability with no shared affordance.
    @MainActor @Test func viewOnlyExceptionsAreStillNeeded() throws {
        let manifest = try loadCapabilityManifest()
        let byID = Dictionary(uniqueKeysWithValues: manifest.capabilities.map { ($0.id, $0) })
        let shared = sharedAffordances()

        for id in viewOnlyCapabilities {
            guard let c = byID[id] else {
                Issue.record("viewOnlyCapabilities has stale id `\(id)` — not in the manifest")
                continue
            }
            #expect(
                c.ios == "supported" || c.macos == "supported",
                "viewOnlyCapabilities lists `\(id)` but it is not GUI-`supported` (iOS=\(c.ios), macOS=\(c.macos)) — the exception is stale; remove it"
            )
            #expect(
                !shared.contains(id),
                "viewOnlyCapabilities lists `\(id)` but it now has a shared affordance — drop the exception and rely on the shared registry"
            )
        }
    }
}
