import Foundation
import Testing
@testable import GraithSessionKit

// Capability manifest ↔ code conformance (issue #1149).
//
// `internal/capabilities/capabilities.json` is the hand-maintained source of
// truth for which capabilities each frontend surfaces. The Go side already
// guards doc ↔ manifest (`TestDocMatchesManifest`); this is the missing
// manifest ↔ code guard, mirroring the #1144 protocol approach:
//
//   - Go projects the manifest to a language-neutral fixture
//     (`Fixtures/capability_manifest.json`, generated by
//     `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`)
//     carrying each capability's iOS + macOS state.
//   - This test decodes that fixture and cross-checks it against
//     `sharedAffordances()` — the set of capabilities the shared
//     `GraithSessionKit` layer actually wires. Since #1147 both apps bind to
//     that one layer (`FleetModel` / `HostConnection` / `TerminalAttachViewModel`
//     / the `GraithHostClient` boundary), so a capability wired there is, by
//     construction, available to both GUIs.
//
// The registry is *compile-anchored*: each entry references the real shared
// symbol behind it, so renaming or deleting the wiring stops this file from
// compiling — the registry can't outlive its code. That closes the gap that
// bit us in #1143 (macOS code shipped, manifest still said `planned`): a wired
// affordance the manifest calls anything but `supported` is now a red test, and
// a manifest that claims `supported` without a backing affordance is too.

// MARK: - Fixture DTOs

private struct CapabilityFixture: Decodable {
    let version: Int
    let capabilities: [CapabilityEntry]
}

private struct CapabilityEntry: Decodable {
    let id: String
    let ios: String
    let macos: String
}

private enum CapabilityFixtureError: Error, CustomStringConvertible {
    case missing
    var description: String {
        "capability_manifest.json not found in the test bundle — check the resources: entry in Package.swift, and regenerate with `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`"
    }
}

private func loadCapabilityManifest() throws -> CapabilityFixture {
    let candidates: [(String, String?)] = [
        ("capability_manifest", "Fixtures"),
        ("capability_manifest", nil),
    ]
    for (resource, subdir) in candidates {
        if let url = Bundle.module.url(forResource: resource, withExtension: "json", subdirectory: subdir) {
            return try JSONDecoder().decode(CapabilityFixture.self, from: try Data(contentsOf: url))
        }
    }
    throw CapabilityFixtureError.missing
}

// MARK: - The shared-layer affordance registry (compile-anchored)

/// The capabilities the shared `GraithSessionKit` layer wires. Each `wire`
/// entry touches the real symbol behind the capability, so a rename/removal is
/// a compile error here — the registry cannot claim a capability the code no
/// longer provides. Returns the set of capability ids for the checks below.
@MainActor
private func sharedAffordances() -> Set<String> {
    var ids: Set<String> = []
    func wire(_ id: String, _ anchor: () -> Void) {
        anchor()
        ids.insert(id)
    }

    // Session lifecycle — FleetModel routes every action to the owning host.
    wire("session.list") { _ = \FleetModel.sessions }
    wire("session.create") { _ = FleetModel.createSession }
    wire("session.stop") { _ = FleetModel.stopSession }
    wire("session.resume") { _ = FleetModel.resumeSession }
    wire("session.restart") { _ = FleetModel.restartSession }
    wire("session.delete") { _ = FleetModel.deleteSession }
    wire("session.rename") { _ = FleetModel.renameSession }
    wire("session.star") { _ = FleetModel.toggleStar }
    wire("session.fork") { _ = FleetModel.forkSession }
    wire("session.migrate") { _ = FleetModel.migrateSession }
    wire("session.repo-list") { _ = HostConnection.repoList }

    // Terminal I/O — the shared attach view-model drives attach/input/resize/detach.
    wire("terminal.attach") { _ = TerminalAttachViewModel.attach }
    wire("terminal.input") { _ = TerminalAttachViewModel.sendRaw }
    wire("terminal.resize") { _ = TerminalAttachViewModel.resize }
    wire("terminal.detach") { _ = TerminalAttachViewModel.detach }
    // logs + screen-snapshot are boundary reads (GraithHostClient); anchor to
    // their wire control-type constants, which exist iff the boundary defines them.
    wire("terminal.logs") { _ = ControlType.logs }
    wire("terminal.screen-snapshot") { _ = ControlType.screenSnapshot }

    // Approvals & pairing.
    wire("approvals.subscribe") { _ = \FleetModel.allApprovals }
    wire("approvals.respond") { _ = HostConnection.respond }
    wire("pairing.request") { _ = ControlType.pairRequest }

    return ids
}

/// Capabilities the manifest may mark `supported` on a GUI without a shared
/// affordance — genuinely per-app view wiring that can't be reflected from the
/// shared layer. Empty today: every GUI-supported capability is shared-routed.
/// Adding an id here is the "explicit, reviewed exception" the issue calls for,
/// not a silent hand-edit.
private let viewOnlyCapabilities: Set<String> = []

/// Capabilities allowed to differ between iOS and macOS. Empty today: #1147
/// made the GUIs parity-by-construction. An intentional divergence must be
/// declared here (with a reason) rather than quietly diverging in the manifest.
private let knownDivergences: Set<String> = []

// MARK: - Tests

struct CapabilityConformanceTests {
    /// The core manifest ↔ code guard. A wired shared affordance must be
    /// `supported` on both GUIs, and a GUI-`supported` capability must have a
    /// backing affordance (or a declared view-only exception).
    @MainActor @Test func manifestMatchesSharedAffordances() throws {
        let manifest = try loadCapabilityManifest()
        let byID = Dictionary(uniqueKeysWithValues: manifest.capabilities.map { ($0.id, $0) })
        let shared = sharedAffordances()

        // Reverse-lie: everything the shared layer wires must be a manifest id
        // and `supported` on both GUIs. This is the #1143 incident as a red test.
        for id in shared.sorted() {
            guard let c = byID[id] else {
                Issue.record("shared affordance `\(id)` is not a capability in the manifest — fix the id in sharedAffordances() or add it to capabilities.json")
                continue
            }
            #expect(
                c.ios == "supported",
                "`\(id)` is wired in GraithSessionKit but the manifest marks iOS `\(c.ios)` — a wired affordance can't be `\(c.ios)`; update capabilities.json + regenerate"
            )
            #expect(
                c.macos == "supported",
                "`\(id)` is wired in GraithSessionKit but the manifest marks macOS `\(c.macos)` — a wired affordance can't be `\(c.macos)`; update capabilities.json + regenerate"
            )
        }

        // Forward-lie: a GUI-`supported` capability must be backed by a shared
        // affordance, or explicitly declared view-only.
        for c in manifest.capabilities where c.ios == "supported" || c.macos == "supported" {
            #expect(
                shared.contains(c.id) || viewOnlyCapabilities.contains(c.id),
                "`\(c.id)` is `supported` on a GUI but nothing declares it: wire it in sharedAffordances() (with a compile anchor) or add it to viewOnlyCapabilities with a reason"
            )
        }
    }

    /// View-level divergence guard. #1147 made the GUIs parity-by-construction,
    /// so a capability surfaced on one app but not the other is a silent drift —
    /// force it to be a declared, reviewed exception.
    @Test func guiParityHolds() throws {
        let manifest = try loadCapabilityManifest()
        for c in manifest.capabilities where !knownDivergences.contains(c.id) {
            #expect(
                c.ios == c.macos,
                "capability `\(c.id)` diverges (iOS=\(c.ios), macOS=\(c.macos)) but is not in knownDivergences — the shared layer is parity-by-construction (#1147); add a reviewed exception if this is intentional"
            )
        }
    }

    /// Sanity: the fixture loads and carries the manifest version the check
    /// speaks, so a future manifest-version bump is noticed here too.
    @Test func fixtureLoads() throws {
        let manifest = try loadCapabilityManifest()
        #expect(!manifest.capabilities.isEmpty)
        #expect(manifest.version == 1, "capability fixture version \(manifest.version) — the conformance check models version 1")
    }

    /// Guards against a stale exception outliving its need: every declared
    /// view-only / divergence id must still be a real capability in the manifest.
    @Test func exceptionsReferenceRealCapabilities() throws {
        let manifest = try loadCapabilityManifest()
        let ids = Set(manifest.capabilities.map(\.id))
        for id in viewOnlyCapabilities {
            #expect(ids.contains(id), "viewOnlyCapabilities has stale id `\(id)` — not in the manifest")
        }
        for id in knownDivergences {
            #expect(ids.contains(id), "knownDivergences has stale id `\(id)` — not in the manifest")
        }
    }
}
