import Foundation
import Testing
@testable import GraithSessionKit

// Capability manifest ↔ shared-layer conformance (issue #1149).
//
// `internal/capabilities/capabilities.json` is the hand-maintained source of
// truth for which capabilities each frontend surfaces. The Go side already
// guards doc ↔ manifest (`TestDocMatchesManifest`); this is the missing
// manifest ↔ code guard, mirroring the #1144 protocol approach:
//
//   - Go projects the manifest to a language-neutral fixture
//     (`Fixtures/capability_manifest.json`, generated by
//     `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`)
//     carrying each capability's iOS + macOS state.
//   - This test decodes that fixture and cross-checks it against
//     `sharedAffordances()` — the set of capabilities the shared
//     `GraithSessionKit` layer wires. Since #1147 both apps bind to that one
//     layer (`FleetModel` / `HostConnection` / `TerminalAttachViewModel` / the
//     `GraithHostClient` boundary), so a capability wired there is *available*
//     to both GUIs.
//
// The registry is *compile-anchored*: each entry references the real shared
// symbol behind it, so renaming or deleting the wiring stops this file from
// compiling — a registered row can't outlive its code.
//
// SCOPE — what this proves, and what it does not (deliberately narrow, cf. the
// #1149 review):
//
//   - Guaranteed: the manifest cannot over- or under-claim relative to the
//     *shared* capability surface. A capability the manifest marks `supported`
//     on a GUI must have a backing shared affordance (or a declared view-only
//     exception); a wired affordance the manifest marks anything but
//     `supported` is a red test; iOS/macOS must stay at parity. A registered
//     row is rot-proof against renames/removals via the compile anchor.
//   - NOT guaranteed: that each app's *views* actually surface the capability.
//     The shared layer is the model surface, not the SwiftUI/AppKit views the
//     apps own on top of it — and surfacing is sometimes a semantic judgment
//     (e.g. iOS surfaces `terminal.logs` / `terminal.screen-snapshot` through
//     the live attach view rather than a dedicated sheet). Per-app view
//     surfacing therefore stays a *reviewed* decision, tracked by the checklist
//     documented in AGENTS.md — a naive view-type anchor would false-positive
//     on the covered-by-attach cases. An automated per-app view-anchor guard is
//     a follow-up, not part of this pass.
//   - Also manual: adding a *new* shared affordance requires adding its row
//     here. The anchor keeps an existing row honest; it cannot discover wiring
//     that was never registered. This is the same discipline as the manifest it
//     guards, now with a compile tripwire on the registered set.

// MARK: - Fixture DTOs

private struct CapabilityFixture: Decodable {
    let version: Int
    let capabilities: [CapabilityEntry]
}

private struct CapabilityEntry: Decodable {
    let id: String
    let ios: String
    let macos: String
}

private enum CapabilityFixtureError: Error, CustomStringConvertible {
    case missing
    var description: String {
        "capability_manifest.json not found in the test bundle — check the resources: entry in Package.swift, and regenerate with `go test ./internal/capabilities -run TestGUIFixtureUpToDate -update`"
    }
}

private func loadCapabilityManifest() throws -> CapabilityFixture {
    let candidates: [(String, String?)] = [
        ("capability_manifest", "Fixtures"),
        ("capability_manifest", nil),
    ]
    for (resource, subdir) in candidates {
        if let url = Bundle.module.url(forResource: resource, withExtension: "json", subdirectory: subdir) {
            return try JSONDecoder().decode(CapabilityFixture.self, from: try Data(contentsOf: url))
        }
    }
    throw CapabilityFixtureError.missing
}

// MARK: - The shared-layer affordance registry (compile-anchored)

/// The capabilities the shared `GraithSessionKit` layer wires. Each `wire`
/// entry touches the real symbol behind the capability, so a rename/removal is
/// a compile error here — the registry cannot claim a capability the code no
/// longer provides. Returns the set of capability ids for the checks below.
@MainActor
private func sharedAffordances() -> Set<String> {
    var ids: Set<String> = []
    func wire(_ id: String, _ anchor: () -> Void) {
        anchor()
        ids.insert(id)
    }

    // Session lifecycle — FleetModel routes every action to the owning host.
    wire("session.list") { _ = \FleetModel.sessions }
    // Sidebar filter/search/view-mode (#906) — shared filter state + pure logic.
    wire("session.filter") { _ = FleetModel.filtered }
    wire("session.create") { _ = FleetModel.createSession }
    wire("session.stop") { _ = FleetModel.stopSession }
    wire("session.resume") { _ = FleetModel.resumeSession }
    wire("session.restart") { _ = FleetModel.restartSession }
    wire("session.delete") { _ = FleetModel.deleteSession }
    wire("session.restore") { _ = FleetModel.restore }
    wire("session.purge") { _ = FleetModel.purge }
    wire("session.rename") { _ = FleetModel.renameSession }
    wire("session.star") { _ = FleetModel.toggleStar }
    wire("session.fork") { _ = FleetModel.forkSession }
    wire("session.migrate") { _ = FleetModel.migrateSession }
    wire("session.set-status") { _ = FleetModel.setStatus }
    wire("session.repo-list") { _ = HostConnection.repoList }

    // Terminal I/O — the shared attach view-model drives attach/input/resize/detach.
    wire("terminal.attach") { _ = TerminalAttachViewModel.attach }
    wire("terminal.input") { _ = TerminalAttachViewModel.sendRaw }
    wire("terminal.resize") { _ = TerminalAttachViewModel.resize }
    wire("terminal.detach") { _ = TerminalAttachViewModel.detach }
    // logs + screen-snapshot are boundary reads (GraithHostClient); anchor to
    // their wire control-type constants, which exist iff the boundary defines them.
    wire("terminal.logs") { _ = ControlType.logs }
    wire("terminal.screen-snapshot") { _ = ControlType.screenSnapshot }

    // Approvals & pairing.
    wire("approvals.subscribe") { _ = \FleetModel.allApprovals }
    wire("approvals.respond") { _ = HostConnection.respond }
    wire("pairing.request") { _ = ControlType.pairRequest }

    // Scenarios — FleetModel aggregates per-host scenarios and routes the
    // human-authorized lifecycle actions to the owning host (#903).
    wire("scenarios.manage") { _ = \FleetModel.hostedScenarios; _ = FleetModel.stopScenario(name:hostID:) }

    return ids
}

/// Capabilities the manifest may mark `supported` on a GUI without a shared
/// affordance — genuinely per-app view wiring that can't be reflected from the
/// shared layer. Empty today: every GUI-supported capability is shared-routed.
/// Adding an id here is the "explicit, reviewed exception" the issue calls for,
/// not a silent hand-edit.
private let viewOnlyCapabilities: Set<String> = []

/// Capabilities allowed to differ between iOS and macOS. Empty today: #1147
/// made the GUIs parity-by-construction. An intentional divergence must be
/// declared here (with a reason) rather than quietly diverging in the manifest.
private let knownDivergences: Set<String> = []

// MARK: - Tests

struct CapabilityConformanceTests {
    /// The core manifest ↔ code guard. A wired shared affordance must be
    /// `supported` on both GUIs, and a GUI-`supported` capability must have a
    /// backing affordance (or a declared view-only exception).
    @MainActor @Test func manifestMatchesSharedAffordances() throws {
        let manifest = try loadCapabilityManifest()
        let byID = Dictionary(uniqueKeysWithValues: manifest.capabilities.map { ($0.id, $0) })
        let shared = sharedAffordances()

        // Reverse-lie: everything the shared layer wires must be a manifest id
        // and `supported` on both GUIs — the #1143 direction (code ahead of the
        // manifest) as a red test, for the capabilities registered here.
        for id in shared.sorted() {
            guard let c = byID[id] else {
                Issue.record("shared affordance `\(id)` is not a capability in the manifest — fix the id in sharedAffordances() or add it to capabilities.json")
                continue
            }
            #expect(
                c.ios == "supported",
                "`\(id)` is wired in GraithSessionKit but the manifest marks iOS `\(c.ios)` — a wired affordance can't be `\(c.ios)`; update capabilities.json + regenerate"
            )
            #expect(
                c.macos == "supported",
                "`\(id)` is wired in GraithSessionKit but the manifest marks macOS `\(c.macos)` — a wired affordance can't be `\(c.macos)`; update capabilities.json + regenerate"
            )
        }

        // Forward-lie: a GUI-`supported` capability must be backed by a shared
        // affordance, or explicitly declared view-only.
        for c in manifest.capabilities where c.ios == "supported" || c.macos == "supported" {
            #expect(
                shared.contains(c.id) || viewOnlyCapabilities.contains(c.id),
                "`\(c.id)` is `supported` on a GUI but nothing declares it: wire it in sharedAffordances() (with a compile anchor) or add it to viewOnlyCapabilities with a reason"
            )
        }
    }

    /// View-level divergence guard. #1147 made the GUIs parity-by-construction,
    /// so a capability surfaced on one app but not the other is a silent drift —
    /// force it to be a declared, reviewed exception.
    @Test func guiParityHolds() throws {
        let manifest = try loadCapabilityManifest()
        for c in manifest.capabilities where !knownDivergences.contains(c.id) {
            #expect(
                c.ios == c.macos,
                "capability `\(c.id)` diverges (iOS=\(c.ios), macOS=\(c.macos)) but is not in knownDivergences — the shared layer is parity-by-construction (#1147); add a reviewed exception if this is intentional"
            )
        }
    }

    /// Sanity: the fixture loads and carries the manifest version the check
    /// speaks, so a future manifest-version bump is noticed here too.
    @Test func fixtureLoads() throws {
        let manifest = try loadCapabilityManifest()
        #expect(!manifest.capabilities.isEmpty)
        #expect(manifest.version == 1, "capability fixture version \(manifest.version) — the conformance check models version 1")
    }

    /// Guards against a stale exception outliving its need. An escape hatch that
    /// no longer describes reality is worse than none — it launders a drift as
    /// "known". So each exception must be a real capability *and* still meet the
    /// condition it exempts:
    ///   - a `knownDivergences` id must actually diverge (iOS != macOS) — once
    ///     parity is restored the exception is stale and must be removed;
    ///   - a `viewOnlyCapabilities` id must still be GUI-`supported` yet have no
    ///     shared affordance — once it becomes shared (or drops to planned/n/a)
    ///     the exception is stale.
    @MainActor @Test func exceptionsAreStillNeeded() throws {
        let manifest = try loadCapabilityManifest()
        let byID = Dictionary(uniqueKeysWithValues: manifest.capabilities.map { ($0.id, $0) })
        let shared = sharedAffordances()

        for id in knownDivergences {
            guard let c = byID[id] else {
                Issue.record("knownDivergences has stale id `\(id)` — not in the manifest")
                continue
            }
            #expect(
                c.ios != c.macos,
                "knownDivergences lists `\(id)` but iOS==macOS==\(c.ios) — parity holds, so the exception is stale; remove it"
            )
        }

        for id in viewOnlyCapabilities {
            guard let c = byID[id] else {
                Issue.record("viewOnlyCapabilities has stale id `\(id)` — not in the manifest")
                continue
            }
            #expect(
                c.ios == "supported" || c.macos == "supported",
                "viewOnlyCapabilities lists `\(id)` but it is not GUI-`supported` (iOS=\(c.ios), macOS=\(c.macos)) — the exception is stale; remove it"
            )
            #expect(
                !shared.contains(id),
                "viewOnlyCapabilities lists `\(id)` but it now has a shared affordance — drop the exception and rely on the shared registry"
            )
        }
    }
}
