version: 2

builds:
  - main: ./cmd/graith
    binary: gr-dev
    ldflags:
      - -s -w
      - -X github.com/d0ugal/graith/internal/version.Version={{.Version}}
      - -X github.com/d0ugal/graith/internal/version.CommitSHA={{.Commit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "graith-dev_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true

snapshot:
  version_template: "{{ incpatch .Version }}-dev.{{ .ShortCommit }}"
