import Foundation
import Testing
@testable import GraithProtocol

// Cross-language protocol conformance (issue #1129).
//
// The Go side is the source of truth for the wire protocol's shape. It emits a
// language-neutral manifest (`Fixtures/protocol_manifest.json`, generated by
// `go test ./internal/protocol -run TestManifestUpToDate -update`) listing every
// wire struct, its JSON fields, and — per type — whether Swift is expected to
// model it (`required` / `planned` / `na`).
//
// These tests decode that fixture and prove Messages.swift satisfies every
// `required` type: a decoder is registered for it, and it accepts a JSON
// instance synthesized from the manifest's field list. When Go adds a new
// `required` message (or renames/retypes a required field), this suite goes red
// until Messages.swift catches up — the drift guard the issue asks for.
//
// The Go-side TestManifestUpToDate is the complementary guard: it fails on
// *every* Go PR if messages.go changed without regenerating the fixture, so a
// Go-only change can't slip past the paths-filtered gui/ Swift CI.

// MARK: - Manifest DTOs (decode the committed fixture)

private struct ManifestDTO: Decodable {
    let protocolVersion: String
    let types: [ManifestTypeDTO]

    enum CodingKeys: String, CodingKey {
        case protocolVersion = "protocol_version"
        case types
    }
}

private struct ManifestTypeDTO: Decodable {
    let name: String
    let swift: String        // required | planned | na
    let swiftType: String?
    let fields: [ManifestFieldDTO]

    enum CodingKeys: String, CodingKey {
        case name, swift, fields
        case swiftType = "swift_type"
    }
}

private struct ManifestFieldDTO: Decodable {
    let name: String
    let type: FieldTypeDTO
    let optional: Bool
}

private final class FieldTypeDTO: Decodable {
    let kind: String          // string | int | float | bool | raw | map | array | object
    let elem: FieldTypeDTO?   // array element type
    let ref: String?          // object → referenced type name
}

// MARK: - Fixture loading

private func loadManifest() throws -> ManifestDTO {
    let candidates: [(String, String?)] = [
        ("protocol_manifest", "Fixtures"),
        ("protocol_manifest", nil),
    ]
    for (resource, subdir) in candidates {
        if let url = Bundle.module.url(forResource: resource, withExtension: "json", subdirectory: subdir) {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(ManifestDTO.self, from: data)
        }
    }
    throw ConformanceError.fixtureMissing
}

private enum ConformanceError: Error, CustomStringConvertible {
    case fixtureMissing
    var description: String {
        "protocol_manifest.json not found in the test bundle — check the resources: entry in Package.swift"
    }
}

// MARK: - Swift decoder registry

/// A type-erased "can this JSON decode into the Swift type?" probe.
private struct DecodeProbe {
    let decode: (Data) throws -> Void
}

private func probe<T: Decodable>(_ type: T.Type) -> DecodeProbe {
    DecodeProbe { data in _ = try JSONDecoder().decode(T.self, from: data) }
}

/// Maps each Go wire-type name the manifest marks `required` to the Swift type
/// that satisfies it. Several Go types deliberately consolidate onto one Swift
/// shape (SessionScopeMsg / SessionIDMsg / EmptyMsg). Keep this in step with the
/// `required` rows of `swiftAnnotations` in internal/protocol/manifest.go — the
/// tests below cross-check both directions so a mismatch fails loudly.
private let swiftDecoders: [String: DecodeProbe] = [
    // Handshake.
    "HandshakeMsg": probe(HandshakeMsg.self),
    "HandshakeOkMsg": probe(HandshakeOkMsg.self),
    "HandshakeErrMsg": probe(HandshakeErrMsg.self),

    // Lifecycle / control (client -> daemon).
    "CreateMsg": probe(CreateMsg.self),
    "ForkMsg": probe(ForkMsg.self),
    "MigrateMsg": probe(MigrateMsg.self),
    "AttachMsg": probe(AttachMsg.self),
    "RenameMsg": probe(RenameMsg.self),
    "SetStatusMsg": probe(SetStatusMsg.self),
    "TypeMsg": probe(TypeMsg.self),
    "ResizeMsg": probe(ResizeMsg.self),
    "LogsMsg": probe(LogsMsg.self),

    // stop / delete / restart → SessionScopeMsg.
    "StopMsg": probe(SessionScopeMsg.self),
    "DeleteMsg": probe(SessionScopeMsg.self),
    "RestartMsg": probe(SessionScopeMsg.self),

    // Bare {session_id} requests → SessionIDMsg.
    "InterruptMsg": probe(SessionIDMsg.self),
    "ResumeMsg": probe(SessionIDMsg.self),
    "StarMsg": probe(SessionIDMsg.self),
    "UnstarMsg": probe(SessionIDMsg.self),
    "StatusRequestMsg": probe(SessionIDMsg.self),
    "ScreenPreviewMsg": probe(SessionIDMsg.self),
    "ScreenSnapshotMsg": probe(SessionIDMsg.self),

    // No-payload requests → EmptyMsg.
    "ListMsg": probe(EmptyMsg.self),
    "MCPListMsg": probe(EmptyMsg.self),
    "ScenarioListMsg": probe(EmptyMsg.self),
    "TriggerListMsg": probe(EmptyMsg.self),
    "PairListMsg": probe(EmptyMsg.self),

    // Session model (daemon -> client).
    "SessionListMsg": probe(SessionListMsg.self),
    "SessionInfo": probe(SessionInfo.self),
    "PRInfo": probe(PRInfo.self),
    "CIInfo": probe(CIInfo.self),
    "IncludedRepoInfo": probe(IncludedRepoInfo.self),
    "DetachedMsg": probe(DetachedMsg.self),
    "ErrorMsg": probe(ErrorMsg.self),

    // Screen peek.
    "ScreenPreviewResponseMsg": probe(ScreenPreviewResponseMsg.self),
    "ScreenSnapshotResponseMsg": probe(ScreenSnapshotResponseMsg.self),

    // Approvals.
    "ApprovalInfo": probe(ApprovalInfo.self),
    "ApprovalNotificationMsg": probe(ApprovalNotificationMsg.self),
    "ApprovalRespondMsg": probe(ApprovalRespondMsg.self),
    "ApprovalSubscribeMsg": probe(ApprovalSubscribeMsg.self),

    // Pairing + proof-of-possession.
    "PairRequestMsg": probe(PairRequestMsg.self),
    "PairResponseMsg": probe(PairResponseMsg.self),
    "PairApproveMsg": probe(PairApproveMsg.self),
    "PairListResponseMsg": probe(PairListResponseMsg.self),
    "PairPending": probe(PairPending.self),
    "PairedDeviceInfo": probe(PairedDeviceInfo.self),
    "PairRevokeMsg": probe(PairRevokeMsg.self),
    "AuthChallengeMsg": probe(AuthChallengeMsg.self),
    "AuthProofMsg": probe(AuthProofMsg.self),

    // Remote-create repo picker.
    "RepoListMsg": probe(RepoListMsg.self),
    "RepoListResponseMsg": probe(RepoListResponseMsg.self),
    "RepoEntry": probe(RepoEntry.self),
]

// MARK: - JSON synthesis from the manifest

/// Builds a JSON instance for `type` from the manifest's field list. All fields
/// (optional and required) are populated with placeholder values so every wire
/// key is present — this exercises a Swift type's required properties and its
/// coding keys. Empty arrays and recursively-synthesized objects keep it valid
/// without needing real data.
private func synthesize(_ typeName: String, in typesByName: [String: ManifestTypeDTO], visiting: Set<String> = []) -> [String: Any] {
    guard let t = typesByName[typeName], !visiting.contains(typeName) else {
        return [:]
    }
    var next = visiting
    next.insert(typeName)

    var obj: [String: Any] = [:]
    for field in t.fields {
        obj[field.name] = value(for: field.type, in: typesByName, visiting: next)
    }
    return obj
}

private func value(for ft: FieldTypeDTO, in typesByName: [String: ManifestTypeDTO], visiting: Set<String>) -> Any {
    switch ft.kind {
    case "string": return "x"
    case "int": return 1
    case "float": return 1.0
    case "bool": return true
    case "raw", "map": return [String: Any]()
    case "array": return [Any]() // empty array decodes into any [T]
    case "object": return synthesize(ft.ref ?? "", in: typesByName, visiting: visiting)
    default: return NSNull()
    }
}

// MARK: - Tests

struct ManifestConformanceTests {
    /// Every `required` Go type must have a registered Swift decoder, and a JSON
    /// instance synthesized from the manifest must decode into it. This is the
    /// guard that turns red when Go adds a required message (or a required field)
    /// Messages.swift doesn't yet satisfy.
    @Test func requiredTypesDecodeFromManifest() throws {
        let manifest = try loadManifest()
        let typesByName = Dictionary(uniqueKeysWithValues: manifest.types.map { ($0.name, $0) })

        var checked = 0
        for t in manifest.types where t.swift == "required" {
            guard let decoder = swiftDecoders[t.name] else {
                Issue.record("""
                    Go type `\(t.name)` is marked `required` (expected Swift: \(t.swiftType ?? "?")) \
                    but no Swift decoder is registered in swiftDecoders — Messages.swift is behind the \
                    manifest. Model it and add a probe, or reclassify it in manifest.go.
                    """)
                continue
            }

            let obj = synthesize(t.name, in: typesByName)
            let data: Data
            do {
                data = try JSONSerialization.data(withJSONObject: obj)
            } catch {
                Issue.record("Failed to synthesize JSON for `\(t.name)`: \(error)")
                continue
            }

            do {
                try decoder.decode(data)
            } catch {
                Issue.record("""
                    Swift decoder for Go type `\(t.name)` (\(t.swiftType ?? "?")) rejected a manifest-\
                    synthesized instance: \(error). A required field likely diverged — reconcile \
                    Messages.swift with messages.go.
                    """)
            }
            checked += 1
        }

        #expect(checked > 0, "no required types found in the manifest — fixture likely failed to load")
    }

    /// Every registered Swift decoder must correspond to a `required` manifest
    /// entry. Catches the reverse drift: a probe left for a type the manifest no
    /// longer marks required (renamed, reclassified, or a typo'd key).
    @Test func registeredDecodersAreAllRequired() throws {
        let manifest = try loadManifest()
        let required = Set(manifest.types.filter { $0.swift == "required" }.map(\.name))

        for name in swiftDecoders.keys {
            #expect(
                required.contains(name),
                "swiftDecoders has an entry for `\(name)` but the manifest does not mark it `required` — remove the probe or fix the annotation in manifest.go"
            )
        }
    }

    /// Sanity: the fixture loads and carries the protocol version the Swift
    /// client speaks, so a major-version bump is noticed here too.
    @Test func manifestLoadsAndVersionMatches() throws {
        let manifest = try loadManifest()
        #expect(!manifest.types.isEmpty)
        #expect(
            versionCompatible(manifest.protocolVersion),
            "manifest protocol_version \(manifest.protocolVersion) is incompatible with Swift protocolVersion \(protocolVersion)"
        )
    }
}
