package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/d0ugal/graith/internal/config"
	"github.com/prometheus/common/model"
	"github.com/spf13/cobra"
)

const (
	defaultCollectorScrapeInterval       = "15s"
	defaultCollectorOTLPGRPCListen       = "127.0.0.1:4317"
	defaultCollectorOTLPHTTPListen       = "127.0.0.1:4318"
	defaultCollectorOTLPHTTPTracesPath   = "/v1/traces"
	defaultCollectorMetricsRemoteWrite   = "${env:GRAITH_MIMIR_REMOTE_WRITE_URL}"
	defaultCollectorMetricsAuthHeader    = "${env:GRAITH_MIMIR_AUTH_HEADER}"
	defaultCollectorOTLPHTTPEndpoint     = "${env:GRAITH_OTLP_HTTP_ENDPOINT}"
	defaultCollectorOTLPHTTPAuthHeader   = "${env:GRAITH_OTLP_AUTH_HEADER}"
	defaultCollectorReceiverTLSCertFile  = "${env:GRAITH_OTLP_RECEIVER_TLS_CERT_FILE}"
	defaultCollectorReceiverTLSKeyFile   = "${env:GRAITH_OTLP_RECEIVER_TLS_KEY_FILE}"
	defaultCollectorMemoryLimitMiB       = 256
	defaultCollectorMemorySpikeLimitMiB  = 64
	defaultCollectorRemoteWriteQueueSize = 10000
	defaultCollectorOTLPQueueSize        = 1000
)

type otelCollectorRenderOptions struct {
	includeDaemonLogs     bool
	scrapeInterval        string
	otlpGRPCListen        string
	otlpGRPCTLS           bool
	otlpHTTPListen        string
	otlpHTTPTracesPath    string
	otlpHTTPTLS           bool
	metricsRemoteWriteURL string
	metricsAuthHeader     string
	otlpHTTPEndpoint      string
	otlpAuthHeader        string
}

var configRenderOTelCollectorOpts = defaultOTelCollectorRenderOptions()

var configRenderCmd = &cobra.Command{
	Use:   "render",
	Short: "Render derived configuration files",
}

var configRenderOTelCollectorCmd = &cobra.Command{
	Use:     "otelcol",
	Aliases: []string{"otel-collector", "otelcol-contrib"},
	Short:   "Render OpenTelemetry Collector config for Graith telemetry",
	Args:    cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runConfigRenderOTelCollector(cmd)
	},
}

func defaultOTelCollectorRenderOptions() otelCollectorRenderOptions {
	return otelCollectorRenderOptions{
		scrapeInterval:        defaultCollectorScrapeInterval,
		otlpGRPCListen:        defaultCollectorOTLPGRPCListen,
		otlpHTTPListen:        defaultCollectorOTLPHTTPListen,
		otlpHTTPTracesPath:    defaultCollectorOTLPHTTPTracesPath,
		metricsRemoteWriteURL: defaultCollectorMetricsRemoteWrite,
		metricsAuthHeader:     defaultCollectorMetricsAuthHeader,
		otlpHTTPEndpoint:      defaultCollectorOTLPHTTPEndpoint,
		otlpAuthHeader:        defaultCollectorOTLPHTTPAuthHeader,
	}
}

func runConfigRenderOTelCollector(cmd *cobra.Command) error {
	target := cfgFile
	if target == "" {
		target = paths.ConfigFile
	}

	effectiveCfg, err := config.LoadOrDefault(target)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	renderPaths := paths
	if renderPaths.DataDir == "" {
		renderPaths, err = config.ResolvePaths()
		if err != nil {
			return err
		}
	}

	if effectiveCfg.DataDir != "" {
		renderPaths = renderPaths.WithDataDir(effectiveCfg.DataDir)
	}

	renderOpts := configRenderOTelCollectorOpts
	if !cmd.Flags().Changed("otlp-grpc-listen") {
		renderOpts.otlpGRPCListen = ""
	}

	if !cmd.Flags().Changed("otlp-http-listen") {
		renderOpts.otlpHTTPListen = ""
	}

	if !cmd.Flags().Changed("otlp-http-traces-path") {
		renderOpts.otlpHTTPTracesPath = ""
	}

	text, err := renderOTelCollectorConfig(*effectiveCfg, renderPaths, renderOpts)
	if err != nil {
		return err
	}

	if _, err := fmt.Fprint(cmd.OutOrStdout(), text); err != nil {
		return err
	}

	return nil
}

func renderOTelCollectorConfig(cfg config.Config, paths config.Paths, opts otelCollectorRenderOptions) (string, error) {
	opts, err := opts.withDefaults(cfg)
	if err != nil {
		return "", err
	}

	if err := opts.validate(); err != nil {
		return "", err
	}

	if strings.TrimSpace(paths.DataDir) == "" {
		return "", errors.New("data dir is required to render OTel Collector config")
	}

	if opts.includeDaemonLogs {
		if strings.TrimSpace(paths.DaemonLog) == "" {
			return "", errors.New("daemon log path is required to render daemon log tailing")
		}

		if strings.TrimSpace(paths.DaemonStderrLogPath()) == "" {
			return "", errors.New("daemon stderr log path is required to render daemon log tailing")
		}
	}

	metricsTarget, err := collectorScrapeTarget(cfg.Telemetry.Metrics.BindAddressOrDefault())
	if err != nil {
		return "", err
	}

	metricsPath := cfg.Telemetry.Metrics.PathOrDefault()
	storageDir := filepath.Join(paths.DataDir, "otelcol")
	promRemoteWriteWALDir := filepath.Join(storageDir, "prometheus-remote-write-wal")
	fileStorageDir := filepath.Join(storageDir, "file-storage")

	var b strings.Builder

	b.WriteString("# Generated by `gr config render otelcol`.\n")
	b.WriteString("# This file does not enable Graith telemetry, start a collector, or ship data by itself.\n")
	b.WriteString("# Enable [telemetry.metrics] and [telemetry.tracing] in config.toml, then run `gr daemon restart`.\n")
	b.WriteString("# Session scrollback logs are intentionally excluded. Daemon log tailing is included only with --include-daemon-logs.\n")
	b.WriteString("# Queue/retry guidance: tune queue sizes, retry windows, and optional WAL/persistent queues for your backend.\n")
	b.WriteString("# Requires otelcol-contrib, or a custom Collector distribution with prometheus and prometheus_remote_write; daemon logs also need file_log and file_storage.\n")
	b.WriteString("# The remote exporter placeholders below read backend destinations and credentials from the collector process environment.\n\n")

	if opts.includeDaemonLogs {
		b.WriteString("extensions:\n")
		b.WriteString("  file_storage/graith:\n")
		b.WriteString("    directory: " + yamlString(fileStorageDir) + "\n")
		b.WriteString("    create_directory: true\n\n")
	}

	b.WriteString("receivers:\n")

	if !cfg.Telemetry.Metrics.Enabled {
		b.WriteString("  # [telemetry.metrics] enabled is false; set it to true and restart Graith before running the collector.\n")
	}

	b.WriteString("  prometheus/graith:\n")
	b.WriteString("    config:\n")
	b.WriteString("      scrape_configs:\n")
	b.WriteString("        - job_name: \"graith\"\n")
	b.WriteString("          scrape_interval: " + yamlString(opts.scrapeInterval) + "\n")
	b.WriteString("          metrics_path: " + yamlString(metricsPath) + "\n")
	b.WriteString("          static_configs:\n")
	b.WriteString("            - targets: [" + yamlString(metricsTarget) + "]\n")
	b.WriteString("\n")

	if !cfg.Telemetry.Tracing.Enabled {
		b.WriteString("  # [telemetry.tracing] enabled is false; set it to true and restart Graith before running the collector.\n")
	}

	b.WriteString("  otlp/graith:\n")
	b.WriteString("    protocols:\n")
	b.WriteString("      grpc:\n")
	writeCollectorNonLoopbackWarning(&b, "        ", opts.otlpGRPCListen)
	b.WriteString("        endpoint: " + yamlString(opts.otlpGRPCListen) + "\n")

	if opts.otlpGRPCTLS {
		b.WriteString("        # Graith's local gRPC trace endpoint uses TLS; set these paths in the collector environment.\n")
		writeCollectorReceiverTLSBlock(&b, "        ")
	}

	b.WriteString("      http:\n")
	writeCollectorNonLoopbackWarning(&b, "        ", opts.otlpHTTPListen)
	b.WriteString("        endpoint: " + yamlString(opts.otlpHTTPListen) + "\n")
	b.WriteString("        traces_url_path: " + yamlString(opts.otlpHTTPTracesPath) + "\n")

	if opts.otlpHTTPTLS {
		b.WriteString("        # Graith's local HTTP trace endpoint uses TLS; set these paths in the collector environment.\n")
		writeCollectorReceiverTLSBlock(&b, "        ")
	}

	if opts.includeDaemonLogs {
		b.WriteString("\n")
		b.WriteString("  file_log/graith_daemon:\n")
		b.WriteString("    # Also requires the file_log receiver and file_storage extension from otelcol-contrib.\n")
		b.WriteString("    include:\n")
		b.WriteString("      - " + yamlString(paths.DaemonLog) + "\n")
		b.WriteString("      - " + yamlString(paths.DaemonStderrLogPath()) + "\n")
		b.WriteString("    start_at: end\n")
		b.WriteString("    include_file_path: true\n")
		b.WriteString("    storage: file_storage/graith\n")
		b.WriteString("    attributes:\n")
		b.WriteString("      graith.log.scope: daemon\n")
		b.WriteString("    resource:\n")
		b.WriteString("      service.name: graith-daemon\n")
		b.WriteString("    retry_on_failure:\n")
		b.WriteString("      enabled: true\n")
		b.WriteString("      initial_interval: 1s\n")
		b.WriteString("      max_interval: 30s\n")
		b.WriteString("      max_elapsed_time: 5m\n")
	}

	b.WriteString("\nprocessors:\n")
	b.WriteString("  memory_limiter:\n")
	b.WriteString("    check_interval: 1s\n")
	fmt.Fprintf(&b, "    limit_mib: %d\n", defaultCollectorMemoryLimitMiB)
	fmt.Fprintf(&b, "    spike_limit_mib: %d\n", defaultCollectorMemorySpikeLimitMiB)
	b.WriteString("  batch:\n")
	b.WriteString("    timeout: 5s\n")
	b.WriteString("    send_batch_size: 1024\n")
	b.WriteString("\nexporters:\n")
	b.WriteString("  prometheus_remote_write/graith:\n")
	b.WriteString("    endpoint: " + yamlString(opts.metricsRemoteWriteURL) + "\n")
	b.WriteString("    headers:\n")
	b.WriteString("      Authorization: " + yamlString(opts.metricsAuthHeader) + "\n")
	b.WriteString("    remote_write_queue:\n")
	b.WriteString("      enabled: true\n")
	fmt.Fprintf(&b, "      queue_size: %d\n", defaultCollectorRemoteWriteQueueSize)
	b.WriteString("      num_consumers: 5\n")
	b.WriteString("    retry_on_failure:\n")
	b.WriteString("      enabled: true\n")
	b.WriteString("      initial_interval: 5s\n")
	b.WriteString("      max_interval: 30s\n")
	b.WriteString("      max_elapsed_time: 5m\n")
	b.WriteString("    # For crash-resilient metrics delivery, create this directory and enable WAL:\n")
	b.WriteString("    # wal:\n")
	b.WriteString("    #   directory: " + yamlString(promRemoteWriteWALDir) + "\n")
	b.WriteString("\n")
	b.WriteString("  otlp_http/graith:\n")
	b.WriteString("    endpoint: " + yamlString(opts.otlpHTTPEndpoint) + "\n")
	b.WriteString("    headers:\n")
	b.WriteString("      Authorization: " + yamlString(opts.otlpAuthHeader) + "\n")
	b.WriteString("    sending_queue:\n")
	b.WriteString("      enabled: true\n")
	fmt.Fprintf(&b, "      queue_size: %d\n", defaultCollectorOTLPQueueSize)
	b.WriteString("    retry_on_failure:\n")
	b.WriteString("      enabled: true\n")
	b.WriteString("      initial_interval: 5s\n")
	b.WriteString("      max_interval: 30s\n")
	b.WriteString("      max_elapsed_time: 5m\n")

	b.WriteString("\nservice:\n")

	if opts.includeDaemonLogs {
		b.WriteString("  extensions: [file_storage/graith]\n")
	}

	b.WriteString("  pipelines:\n")
	b.WriteString("    metrics/graith:\n")
	b.WriteString("      receivers: [prometheus/graith]\n")
	b.WriteString("      processors: [memory_limiter, batch]\n")
	b.WriteString("      exporters: [prometheus_remote_write/graith]\n")
	b.WriteString("    traces/graith:\n")
	b.WriteString("      receivers: [otlp/graith]\n")
	b.WriteString("      processors: [memory_limiter, batch]\n")
	b.WriteString("      exporters: [otlp_http/graith]\n")

	if opts.includeDaemonLogs {
		b.WriteString("    logs/graith_daemon:\n")
		b.WriteString("      receivers: [file_log/graith_daemon]\n")
		b.WriteString("      processors: [memory_limiter, batch]\n")
		b.WriteString("      exporters: [otlp_http/graith]\n")
	}

	return b.String(), nil
}

func (o otelCollectorRenderOptions) withDefaults(cfg config.Config) (otelCollectorRenderOptions, error) {
	defaults := defaultOTelCollectorRenderOptions()

	if strings.TrimSpace(o.scrapeInterval) == "" {
		o.scrapeInterval = defaults.scrapeInterval
	}

	if strings.TrimSpace(o.otlpGRPCListen) == "" {
		listen, tls, err := defaultOTLPGRPCListen(cfg)
		if err != nil {
			return otelCollectorRenderOptions{}, err
		}

		o.otlpGRPCListen = listen
		o.otlpGRPCTLS = tls
	} else if !o.otlpGRPCTLS {
		o.otlpGRPCTLS = defaultOTLPGRPCTLS(cfg)
	}

	if strings.TrimSpace(o.otlpHTTPListen) == "" {
		listen, tracesPath, tls, err := defaultOTLPHTTPListen(cfg)
		if err != nil {
			return otelCollectorRenderOptions{}, err
		}

		o.otlpHTTPListen = listen
		o.otlpHTTPTLS = tls

		if strings.TrimSpace(o.otlpHTTPTracesPath) == "" {
			o.otlpHTTPTracesPath = tracesPath
		}
	} else if !o.otlpHTTPTLS {
		o.otlpHTTPTLS = defaultOTLPHTTPTLS(cfg)
	}

	if strings.TrimSpace(o.otlpHTTPTracesPath) == "" {
		o.otlpHTTPTracesPath = defaultOTLPHTTPTracePath(cfg)
	}

	if strings.TrimSpace(o.metricsRemoteWriteURL) == "" {
		o.metricsRemoteWriteURL = defaults.metricsRemoteWriteURL
	}

	if strings.TrimSpace(o.metricsAuthHeader) == "" {
		o.metricsAuthHeader = defaults.metricsAuthHeader
	}

	if strings.TrimSpace(o.otlpHTTPEndpoint) == "" {
		o.otlpHTTPEndpoint = defaults.otlpHTTPEndpoint
	}

	if strings.TrimSpace(o.otlpAuthHeader) == "" {
		o.otlpAuthHeader = defaults.otlpAuthHeader
	}

	return o, nil
}

func (o otelCollectorRenderOptions) validate() error {
	if d, err := model.ParseDuration(o.scrapeInterval); err != nil {
		return fmt.Errorf("--scrape-interval %q: %w", o.scrapeInterval, err)
	} else if d <= 0 {
		return fmt.Errorf("--scrape-interval %q: must be greater than zero", o.scrapeInterval)
	}

	for _, endpoint := range []struct {
		name  string
		value string
	}{
		{"--otlp-grpc-listen", o.otlpGRPCListen},
		{"--otlp-http-listen", o.otlpHTTPListen},
	} {
		if err := validateCollectorListenAddress(endpoint.value); err != nil {
			return fmt.Errorf("%s %q: %w", endpoint.name, endpoint.value, err)
		}
	}

	if o.otlpGRPCListen == o.otlpHTTPListen {
		return fmt.Errorf("--otlp-grpc-listen and --otlp-http-listen must be different; both are %q", o.otlpGRPCListen)
	}

	if !strings.HasPrefix(o.otlpHTTPTracesPath, "/") {
		return fmt.Errorf("--otlp-http-traces-path %q: must start with /", o.otlpHTTPTracesPath)
	}

	return nil
}

func defaultOTLPGRPCListen(cfg config.Config) (string, bool, error) {
	if cfg.Telemetry.Tracing.ProtocolOrDefault() != config.TelemetryTracingProtocolGRPC {
		return defaultCollectorOTLPGRPCListen, false, nil
	}

	endpoint := strings.TrimSpace(cfg.Telemetry.Tracing.Endpoint)
	if endpoint == "" {
		return defaultCollectorOTLPGRPCListen, false, nil
	}

	host, port, err := net.SplitHostPort(endpoint)
	if err != nil {
		return "", false, fmt.Errorf("telemetry.tracing.endpoint %q: gRPC collector receiver endpoints must be host:port", endpoint)
	}

	if !alloyLoopbackHost(host) {
		return "", false, fmt.Errorf("telemetry.tracing.endpoint %q is not loopback; configure Graith to send traces to a local OTel Collector receiver such as %q or pass --otlp-grpc-listen", endpoint, defaultCollectorOTLPGRPCListen)
	}

	return net.JoinHostPort(host, port), !cfg.Telemetry.Tracing.Insecure, nil
}

func defaultOTLPHTTPListen(cfg config.Config) (string, string, bool, error) {
	if cfg.Telemetry.Tracing.ProtocolOrDefault() != config.TelemetryTracingProtocolHTTPProtobuf {
		return defaultCollectorOTLPHTTPListen, defaultCollectorOTLPHTTPTracesPath, false, nil
	}

	raw := strings.TrimSpace(cfg.Telemetry.Tracing.Endpoint)
	if raw == "" {
		return defaultCollectorOTLPHTTPListen, defaultCollectorOTLPHTTPTracesPath, false, nil
	}

	u, err := url.Parse(raw)
	if err != nil || u.Host == "" {
		return "", "", false, fmt.Errorf("telemetry.tracing.endpoint %q: HTTP collector receiver endpoints must be URLs with a loopback host:port", raw)
	}

	host := u.Hostname()

	port := u.Port()
	if port == "" {
		return "", "", false, fmt.Errorf("telemetry.tracing.endpoint %q: HTTP collector receiver endpoints must include a port such as %q", raw, "http://127.0.0.1:4318/v1/traces")
	}

	if !alloyLoopbackHost(host) {
		return "", "", false, fmt.Errorf("telemetry.tracing.endpoint %q is not loopback; configure Graith to send traces to a local OTel Collector receiver such as %q or pass --otlp-http-listen", raw, "http://127.0.0.1:4318/v1/traces")
	}

	if u.RawQuery != "" || u.Fragment != "" {
		return "", "", false, fmt.Errorf("telemetry.tracing.endpoint %q: query strings and fragments are not supported for collector receiver derivation", raw)
	}

	tracesPath := u.EscapedPath()
	if tracesPath == "" || tracesPath == "/" {
		tracesPath = defaultCollectorOTLPHTTPTracesPath
	}

	return net.JoinHostPort(host, port), tracesPath, u.Scheme == "https", nil
}

func defaultOTLPGRPCTLS(cfg config.Config) bool {
	return cfg.Telemetry.Tracing.ProtocolOrDefault() == config.TelemetryTracingProtocolGRPC &&
		strings.TrimSpace(cfg.Telemetry.Tracing.Endpoint) != "" &&
		!cfg.Telemetry.Tracing.Insecure
}

func defaultOTLPHTTPTLS(cfg config.Config) bool {
	if cfg.Telemetry.Tracing.ProtocolOrDefault() != config.TelemetryTracingProtocolHTTPProtobuf {
		return false
	}

	u, err := url.Parse(strings.TrimSpace(cfg.Telemetry.Tracing.Endpoint))

	return err == nil && u.Scheme == "https"
}

func defaultOTLPHTTPTracePath(cfg config.Config) string {
	if cfg.Telemetry.Tracing.ProtocolOrDefault() != config.TelemetryTracingProtocolHTTPProtobuf {
		return defaultCollectorOTLPHTTPTracesPath
	}

	u, err := url.Parse(strings.TrimSpace(cfg.Telemetry.Tracing.Endpoint))
	if err != nil || u.Host == "" || !alloyLoopbackHost(u.Hostname()) || u.RawQuery != "" || u.Fragment != "" {
		return defaultCollectorOTLPHTTPTracesPath
	}

	tracesPath := u.EscapedPath()
	if tracesPath == "" || tracesPath == "/" {
		return defaultCollectorOTLPHTTPTracesPath
	}

	return tracesPath
}

func collectorScrapeTarget(bindAddress string) (string, error) {
	host, port, err := net.SplitHostPort(bindAddress)
	if err != nil {
		return "", fmt.Errorf("telemetry.metrics.bind_address %q: %w", bindAddress, err)
	}

	if host == "" {
		host = "127.0.0.1"
	} else if ip := net.ParseIP(strings.Trim(host, "[]")); ip != nil && ip.IsUnspecified() {
		if ip.To4() != nil {
			host = "127.0.0.1"
		} else {
			host = "::1"
		}
	}

	return net.JoinHostPort(host, port), nil
}

func writeCollectorReceiverTLSBlock(b *strings.Builder, indent string) {
	b.WriteString(indent + "tls:\n")
	b.WriteString(indent + "  cert_file: " + yamlString(defaultCollectorReceiverTLSCertFile) + "\n")
	b.WriteString(indent + "  key_file: " + yamlString(defaultCollectorReceiverTLSKeyFile) + "\n")
}

func writeCollectorNonLoopbackWarning(b *strings.Builder, indent string, listen string) {
	host, _, err := net.SplitHostPort(listen)
	if err != nil || alloyLoopbackHost(host) {
		return
	}

	b.WriteString(indent + "# Warning: this receiver is not bound to loopback and has no authentication configured.\n")
}

func validateCollectorListenAddress(value string) error {
	host, port, err := net.SplitHostPort(value)
	if err != nil {
		return errors.New("must be in host:port form")
	}

	if strings.TrimSpace(host) == "" || strings.ContainsAny(host, " \t\r\n") {
		return errors.New("host must be non-empty and must not contain whitespace")
	}

	if strings.TrimSpace(port) == "" {
		return errors.New("port is required")
	}

	n, err := strconv.Atoi(port)
	if err != nil {
		return errors.New("port must be numeric")
	}

	if n < 1 || n > 65535 {
		return errors.New("port must be in range 1-65535")
	}

	return nil
}

func yamlString(value string) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}

	return string(data)
}
