package cli

import (
	"errors"
	"fmt"
	"net"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/d0ugal/graith/internal/config"
	"github.com/spf13/cobra"
)

const (
	configAlloyDefaultSignals        = "metrics,traces"
	configAlloyDefaultTraceGRPC      = "127.0.0.1:4317"
	configAlloyDefaultTraceHTTPProto = "http://127.0.0.1:4318/v1/traces"
)

var configAlloySignals = configAlloyDefaultSignals

type alloySignal string

const (
	alloySignalDaemonLogs alloySignal = "daemon-logs"
	alloySignalMetrics    alloySignal = "metrics"
	alloySignalTraces     alloySignal = "traces"
)

var alloySignalOrder = []alloySignal{
	alloySignalDaemonLogs,
	alloySignalMetrics,
	alloySignalTraces,
}

type alloyRenderInput struct {
	Config  *config.Config
	Paths   config.Paths
	Signals []alloySignal
}

type alloyTraceReceiver struct {
	Protocol          string
	Endpoint          string
	TracesPath        string
	DefaultedEndpoint bool
	TLS               bool
}

var configAlloyCmd = &cobra.Command{
	Use:   "alloy",
	Short: "Generate Grafana Alloy config",
	Long: "Generate Grafana Alloy config for local Graith observability collection.\n\n" +
		"The default generated config includes metrics and traces. Add\n" +
		"--signals daemon-logs,metrics,traces to explicitly include raw daemon\n" +
		"log files. Backend\n" +
		"URLs and credentials are emitted as sys.env(...) references for Alloy's\n" +
		"service environment; Graith never reads or inlines Loki, Mimir, or Tempo\n" +
		"secrets. Session scrollback logs are intentionally omitted.",
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		signals, err := parseAlloySignals(configAlloySignals)
		if err != nil {
			return err
		}

		target := cfgFile
		if target == "" {
			target = paths.ConfigFile
		}

		effectiveCfg, err := config.LoadOrDefault(target)
		if err != nil {
			return fmt.Errorf("load config: %w", err)
		}

		resolvedPaths, err := resolvedAlloyPaths(paths, effectiveCfg)
		if err != nil {
			return err
		}

		text, err := renderAlloyConfig(alloyRenderInput{
			Config:  effectiveCfg,
			Paths:   resolvedPaths,
			Signals: signals,
		})
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(cmd.OutOrStdout(), text)

		return err
	},
}

func resolvedAlloyPaths(base config.Paths, cfg *config.Config) (config.Paths, error) {
	if base.DataDir == "" {
		var err error

		base, err = config.ResolvePaths()
		if err != nil {
			return config.Paths{}, err
		}
	}

	if cfg != nil && cfg.DataDir != "" {
		base = base.WithDataDir(cfg.DataDir)
	}

	return base, nil
}

func parseAlloySignals(raw string) ([]alloySignal, error) {
	fields := strings.Split(raw, ",")
	selected := map[alloySignal]bool{}

	for _, field := range fields {
		token := strings.ToLower(strings.TrimSpace(field))
		if token == "" {
			return nil, fmt.Errorf("invalid Alloy signal list %q: empty signal", raw)
		}

		if token == "all" {
			if len(fields) != 1 {
				return nil, errors.New(`invalid Alloy signal list: "all" must be used alone`)
			}

			return append([]alloySignal(nil), alloySignalOrder...), nil
		}

		signal, ok := canonicalAlloySignal(token)
		if !ok {
			return nil, fmt.Errorf("unknown Alloy signal %q (want daemon-logs, metrics, traces, or all)", token)
		}

		selected[signal] = true
	}

	if len(selected) == 0 {
		return nil, errors.New("at least one Alloy signal must be selected")
	}

	out := make([]alloySignal, 0, len(selected))
	for _, signal := range alloySignalOrder {
		if selected[signal] {
			out = append(out, signal)
		}
	}

	return out, nil
}

func canonicalAlloySignal(token string) (alloySignal, bool) {
	switch token {
	case "daemon-logs", "daemon_logs", "logs", "log":
		return alloySignalDaemonLogs, true
	case "metrics", "metric":
		return alloySignalMetrics, true
	case "traces", "trace":
		return alloySignalTraces, true
	default:
		return "", false
	}
}

// renderAlloyConfig intentionally renders only non-secret Graith settings.
// Backend credentials must stay as Alloy sys.env(...) references.
func renderAlloyConfig(input alloyRenderInput) (string, error) {
	if input.Config == nil {
		return "", errors.New("render Alloy config: Graith config is required")
	}

	if len(input.Signals) == 0 {
		return "", errors.New("render Alloy config: at least one signal is required")
	}

	selected := alloySignalSet(input.Signals)

	var b strings.Builder

	b.WriteString("// Generated by `gr config alloy` from resolved Graith config.\n")
	b.WriteString("// Set referenced sys.env(...) values in Alloy's service environment.\n")

	if selected[alloySignalDaemonLogs] {
		b.WriteString("// Daemon logs are included; session scrollback logs are intentionally omitted.\n")
	}

	b.WriteString("\n")

	first := true

	if selected[alloySignalDaemonLogs] {
		if err := renderAlloyDaemonLogs(&b, input.Paths); err != nil {
			return "", err
		}

		first = false
	}

	if selected[alloySignalMetrics] {
		writeAlloySectionBreak(&b, first)

		if err := renderAlloyMetrics(&b, input.Config.Telemetry.Metrics); err != nil {
			return "", err
		}

		first = false
	}

	if selected[alloySignalTraces] {
		writeAlloySectionBreak(&b, first)

		if err := renderAlloyTraces(&b, input.Config.Telemetry.Tracing); err != nil {
			return "", err
		}
	}

	return b.String(), nil
}

func alloySignalSet(signals []alloySignal) map[alloySignal]bool {
	selected := make(map[alloySignal]bool, len(signals))
	for _, signal := range signals {
		selected[signal] = true
	}

	return selected
}

func writeAlloySectionBreak(b *strings.Builder, first bool) {
	if !first {
		b.WriteString("\n")
	}
}

func renderAlloyDaemonLogs(b *strings.Builder, paths config.Paths) error {
	daemonLog := paths.DaemonLog
	if daemonLog == "" && paths.DataDir != "" {
		daemonLog = filepath.Join(paths.DataDir, "daemon.log")
	}

	daemonStderrLog := paths.DaemonStderrLogPath()
	if daemonLog == "" || daemonStderrLog == "" {
		return errors.New("render Alloy daemon logs: resolved daemon log paths are required")
	}

	b.WriteString("loki.source.file \"graith_daemon\" {\n")
	b.WriteString("  targets = [\n")
	writeAlloyLogTarget(b, daemonLog, "daemon")
	writeAlloyLogTarget(b, daemonStderrLog, "daemon-stderr")
	b.WriteString("  ]\n")
	b.WriteString("  forward_to = [loki.write.graith.receiver]\n")
	b.WriteString("\n")
	b.WriteString("  file_match {\n")
	b.WriteString("    enabled = true\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("loki.write \"graith\" {\n")
	b.WriteString("  endpoint {\n")
	b.WriteString("    url = sys.env(\"GRAITH_LOKI_URL\")\n")
	b.WriteString("\n")
	b.WriteString("    basic_auth {\n")
	b.WriteString("      username = sys.env(\"GRAITH_LOKI_USERNAME\")\n")
	b.WriteString("      password = sys.env(\"GRAITH_LOKI_TOKEN\")\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return nil
}

func writeAlloyLogTarget(b *strings.Builder, path string, component string) {
	b.WriteString("    {\n")
	fmt.Fprintf(b, "      \"__path__\"  = %s,\n", alloyQuote(path))
	b.WriteString("      \"job\"       = \"graith\",\n")
	fmt.Fprintf(b, "      \"component\" = %s,\n", alloyQuote(component))
	b.WriteString("    },\n")
}

func renderAlloyMetrics(b *strings.Builder, metrics config.TelemetryMetricsConfig) error {
	scrapeAddress, err := alloyMetricsScrapeAddress(metrics.BindAddressOrDefault())
	if err != nil {
		return err
	}

	if !metrics.Enabled {
		b.WriteString("// [telemetry.metrics] enabled is false; set it to true and restart Graith before running Alloy.\n")
	}

	b.WriteString("prometheus.scrape \"graith\" {\n")
	b.WriteString("  job_name = \"graith\"\n")
	b.WriteString("\n")
	b.WriteString("  targets = [{\n")
	fmt.Fprintf(b, "    \"__address__\" = %s,\n", alloyQuote(scrapeAddress))
	b.WriteString("  }]\n")
	b.WriteString("\n")
	fmt.Fprintf(b, "  metrics_path = %s\n", alloyQuote(metrics.PathOrDefault()))
	b.WriteString("  forward_to   = [prometheus.remote_write.graith.receiver]\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("prometheus.remote_write \"graith\" {\n")
	b.WriteString("  endpoint {\n")
	b.WriteString("    url = sys.env(\"GRAITH_MIMIR_URL\")\n")
	b.WriteString("\n")
	b.WriteString("    basic_auth {\n")
	b.WriteString("      username = sys.env(\"GRAITH_MIMIR_USERNAME\")\n")
	b.WriteString("      password = sys.env(\"GRAITH_MIMIR_TOKEN\")\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return nil
}

func alloyMetricsScrapeAddress(bindAddress string) (string, error) {
	host, port, err := net.SplitHostPort(bindAddress)
	if err != nil {
		return "", fmt.Errorf("render Alloy metrics: parse bind address %q: %w", bindAddress, err)
	}

	switch host {
	case "", "0.0.0.0":
		return net.JoinHostPort("127.0.0.1", port), nil
	case "::":
		return net.JoinHostPort("::1", port), nil
	default:
		return bindAddress, nil
	}
}

func renderAlloyTraces(b *strings.Builder, tracing config.TelemetryTracingConfig) error {
	receiver, err := resolveAlloyTraceReceiver(tracing)
	if err != nil {
		return err
	}

	if !tracing.Enabled {
		b.WriteString("// [telemetry.tracing] enabled is false; set it to true and restart Graith before running Alloy.\n")
	}

	if receiver.DefaultedEndpoint {
		b.WriteString("// Graith tracing has no endpoint configured yet. Before enabling tracing,\n")

		switch receiver.Protocol {
		case config.TelemetryTracingProtocolGRPC:
			b.WriteString("// set [telemetry.tracing] endpoint = \"127.0.0.1:4317\" and insecure = true.\n")
		case config.TelemetryTracingProtocolHTTPProtobuf:
			b.WriteString("// set [telemetry.tracing] endpoint = \"http://127.0.0.1:4318/v1/traces\".\n")
		}
	}

	b.WriteString("otelcol.receiver.otlp \"graith\" {\n")

	switch receiver.Protocol {
	case config.TelemetryTracingProtocolGRPC:
		b.WriteString("  grpc {\n")
		fmt.Fprintf(b, "    endpoint = %s\n", alloyQuote(receiver.Endpoint))
		writeAlloyTLSBlock(b, "    ", receiver.TLS)
		b.WriteString("  }\n")
	case config.TelemetryTracingProtocolHTTPProtobuf:
		b.WriteString("  http {\n")
		fmt.Fprintf(b, "    endpoint        = %s\n", alloyQuote(receiver.Endpoint))
		fmt.Fprintf(b, "    traces_url_path = %s\n", alloyQuote(receiver.TracesPath))
		writeAlloyTLSBlock(b, "    ", receiver.TLS)
		b.WriteString("  }\n")
	default:
		return fmt.Errorf("unsupported tracing protocol %q", receiver.Protocol)
	}

	b.WriteString("\n")
	b.WriteString("  output {\n")
	b.WriteString("    traces = [otelcol.exporter.otlphttp.tempo.input]\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("otelcol.exporter.otlphttp \"tempo\" {\n")
	b.WriteString("  client {\n")
	b.WriteString("    endpoint = sys.env(\"GRAITH_TEMPO_OTLP_ENDPOINT\")\n")
	b.WriteString("    auth     = otelcol.auth.basic.tempo.handler\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("otelcol.auth.basic \"tempo\" {\n")
	b.WriteString("  client_auth {\n")
	b.WriteString("    username = sys.env(\"GRAITH_TEMPO_USERNAME\")\n")
	b.WriteString("    password = sys.env(\"GRAITH_TEMPO_TOKEN\")\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return nil
}

func resolveAlloyTraceReceiver(tracing config.TelemetryTracingConfig) (alloyTraceReceiver, error) {
	protocol := tracing.ProtocolOrDefault()
	endpoint := strings.TrimSpace(tracing.Endpoint)
	defaultedEndpoint := false

	if endpoint == "" {
		defaultedEndpoint = true

		switch protocol {
		case config.TelemetryTracingProtocolGRPC:
			endpoint = configAlloyDefaultTraceGRPC
		case config.TelemetryTracingProtocolHTTPProtobuf:
			endpoint = configAlloyDefaultTraceHTTPProto
		default:
			return alloyTraceReceiver{}, fmt.Errorf("unsupported tracing protocol %q", protocol)
		}
	}

	switch protocol {
	case config.TelemetryTracingProtocolGRPC:
		if err := validateAlloyTraceReceiverHostPort("grpc", endpoint, configAlloyDefaultTraceGRPC); err != nil {
			return alloyTraceReceiver{}, err
		}

		return alloyTraceReceiver{
			Protocol:          protocol,
			Endpoint:          endpoint,
			DefaultedEndpoint: defaultedEndpoint,
			TLS:               !defaultedEndpoint && !tracing.Insecure,
		}, nil
	case config.TelemetryTracingProtocolHTTPProtobuf:
		u, err := url.Parse(endpoint)
		if err != nil {
			return alloyTraceReceiver{}, fmt.Errorf("parse http/protobuf tracing endpoint: %w", err)
		}

		if u.Scheme != "http" && u.Scheme != "https" {
			return alloyTraceReceiver{}, fmt.Errorf("http/protobuf tracing endpoint %q must use http or https", endpoint)
		}

		if u.Host == "" {
			return alloyTraceReceiver{}, fmt.Errorf("http/protobuf tracing endpoint %q must include a host", endpoint)
		}

		host := u.Hostname()
		port := u.Port()

		if port == "" {
			return alloyTraceReceiver{}, fmt.Errorf("http/protobuf tracing endpoint %q must include a loopback host:port listener such as %q", endpoint, configAlloyDefaultTraceHTTPProto)
		}

		receiverEndpoint := net.JoinHostPort(host, port)
		if err := validateAlloyTraceReceiverHostPort("http/protobuf", receiverEndpoint, configAlloyDefaultTraceHTTPProto); err != nil {
			return alloyTraceReceiver{}, err
		}

		if u.RawQuery != "" || u.Fragment != "" {
			return alloyTraceReceiver{}, fmt.Errorf("http/protobuf tracing endpoint %q must not include query or fragment", endpoint)
		}

		path := u.EscapedPath()
		if path == "" || path == "/" {
			path = "/v1/traces"
		}

		return alloyTraceReceiver{
			Protocol:          protocol,
			Endpoint:          receiverEndpoint,
			TracesPath:        path,
			DefaultedEndpoint: defaultedEndpoint,
			TLS:               !defaultedEndpoint && u.Scheme == "https",
		}, nil
	default:
		return alloyTraceReceiver{}, fmt.Errorf("unsupported tracing protocol %q", protocol)
	}
}

func validateAlloyTraceReceiverHostPort(protocol string, endpoint string, example string) error {
	host, _, err := net.SplitHostPort(endpoint)
	if err != nil {
		return fmt.Errorf("%s tracing endpoint %q must be a loopback host:port listener such as %q; or omit traces with --signals daemon-logs,metrics", protocol, endpoint, example)
	}

	if !alloyLoopbackHost(host) {
		return fmt.Errorf("%s tracing endpoint %q is not loopback; configure Graith to send traces to a local Alloy receiver such as %q before generating Alloy config, or omit traces with --signals daemon-logs,metrics", protocol, endpoint, example)
	}

	return nil
}

func alloyLoopbackHost(host string) bool {
	host = strings.Trim(strings.ToLower(host), "[]")
	if host == "localhost" {
		return true
	}

	ip := net.ParseIP(host)

	return ip != nil && ip.IsLoopback()
}

func writeAlloyTLSBlock(b *strings.Builder, indent string, enabled bool) {
	if !enabled {
		return
	}

	b.WriteString("\n")
	fmt.Fprintf(b, "%stls {\n", indent)
	fmt.Fprintf(b, "%s  cert_file = sys.env(\"GRAITH_OTLP_RECEIVER_TLS_CERT_FILE\")\n", indent)
	fmt.Fprintf(b, "%s  key_file  = sys.env(\"GRAITH_OTLP_RECEIVER_TLS_KEY_FILE\")\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

func alloyQuote(value string) string {
	return strconv.Quote(value)
}
