package cli

import (
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var manCmd = &cobra.Command{
	Use:    "man <outdir>",
	Short:  "Generate man pages",
	Long:   "Generate man pages for gr and all its subcommands into the given directory.",
	Args:   cobra.ExactArgs(1),
	Hidden: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		header := &doc.GenManHeader{
			Title:   "GR",
			Section: "1",
			Source:  "graith",
			Manual:  "graith Manual",
			Date:    sourceDate(),
		}

		if err := doc.GenManTree(rootCmd, header, args[0]); err != nil {
			return fmt.Errorf("generating man pages: %w", err)
		}

		return nil
	},
}

// sourceDate returns the date to stamp into generated man pages. It honors
// SOURCE_DATE_EPOCH (the reproducible-builds standard, set from the commit date
// by the release build) so rebuilds of the same commit produce identical
// output.
//
// When the variable is unset it returns nil, leaving cobra to fall back to the
// current time for local development. When it is set but not a valid integer it
// also returns nil, but cobra then re-reads SOURCE_DATE_EPOCH itself and fails
// generation with an "invalid SOURCE_DATE_EPOCH" error — i.e. a garbage value is
// fail-closed, not silently stamped with wall-clock time.
func sourceDate() *time.Time {
	epoch, ok := os.LookupEnv("SOURCE_DATE_EPOCH")
	if !ok {
		return nil
	}

	secs, err := strconv.ParseInt(epoch, 10, 64)
	if err != nil {
		return nil
	}

	t := time.Unix(secs, 0).UTC()

	return &t
}

// registerManCmd registers this command on rootCmd. Called from registerCommands.
func registerManCmd() {
	// Drop cobra's auto-generated HISTORY footer ("<date> Auto generated by
	// spf13/cobra"), which otherwise embeds a wall-clock date and breaks
	// byte-for-byte reproducible packaging. Set here as static command
	// configuration rather than inside RunE so it isn't a per-invocation
	// mutation of the shared rootCmd singleton.
	rootCmd.DisableAutoGenTag = true

	rootCmd.AddCommand(manCmd)
}
