#!/usr/bin/env bash
#
# setup.sh — stand up an isolated graith environment for the demo recording.
#
# Everything runs under the dedicated, fixed `demo` profile (GRAITH_PROFILE=demo),
# so it never touches your real sessions, config, or data:
#   config: ~/.config/graith-demo/config.toml
#   data:   ~/.graith-demo/   (daemon socket, worktrees, state, logs, messages)
#
# Sessions run your real local agents (claude/codex) with your real sandbox —
# both copied from your default graith config — so the demo is the genuine
# article. They start idle (no prompt); the tape attaches and types prompts to
# show real responses. Re-running is safe — it tears down the previous demo
# state first (ownership-guarded).
#
# NOTE: run this *unsandboxed* on your own machine — it starts a daemon (binds a
# unix socket) and creates git worktrees, which a restrictive agent sandbox
# blocks. (The demo's *agents* are still sandboxed; the recording process is not.)

set -euo pipefail

# Fixed, isolated profile. Clear any ambient graith session/agent env so every
# `gr` call targets the demo profile cleanly: an inherited GRAITH_SESSION_ID
# would retarget `gr status`/parent new sessions, and agent-mode would emit JSON
# that the teardown purge loop can't parse.
export GRAITH_PROFILE=demo
export GR_AGENT_MODE=0
unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
      GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

# The default-profile config we copy [agents.*] and [sandbox] from, so the demo
# runs the exact claude/codex you already have, sandboxed the same way.
SRC_CONFIG="${GRAITH_DEMO_SRC_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/graith/config.toml}"

# Fixed harness-owned paths — never from the environment, so nothing can alias a
# real graith data dir under rm -rf (teardown only rm's when it owns them).
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/graith-demo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
DEMO_DATA_DIR="$HOME/.graith-demo"
OWNER_FILE=".graith-demo-owner"
CONFIG_PROOF_FILE=".graith-demo-config-proof"
CONFIG_MARKER="# Generated by demo/setup.sh owner="

# On macOS the CLI's unset-XDG fallback is folded into DEMO_DATA_DIR by the
# data_dir override, so the data marker covers it. On Linux the CLI instead
# falls back to /run/user/<uid>, which this harness cannot safely identify from
# an unset environment. Refuse rather than contact an untracked runtime target.
DEMO_OS="$(uname -s)"
case "$DEMO_OS" in
	Darwin) RUNTIME_DIR="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/graith-demo}" ;;
	Linux)
		if [ -z "${XDG_RUNTIME_DIR:-}" ]; then
			echo "refusing: XDG_RUNTIME_DIR must be set so demo runtime ownership can be verified." >&2
			exit 1
		fi
		RUNTIME_DIR="$XDG_RUNTIME_DIR/graith-demo"
		;;
	*)
		echo "refusing: the demo requires a supported OS sandbox (Darwin or Linux)." >&2
		exit 1
		;;
esac

# The repo the demo sessions "work" on. Safe to override (used only for --repo,
# never for deletion). Its parent is whitelisted in allowed_repo_paths.
DEMO_REPO="${DEMO_REPO:-$REPO_ROOT}"
DEMO_REPO_PARENT="$(cd "$DEMO_REPO/.." && pwd)"

# Print only the [sandbox], [sandbox.*], [agents] and [agents.*] TOML tables
# from $1. Only a well-formed table header ([name] / [[name]], optional trailing
# comment) resets the keep flag — array-continuation lines that start with '['
# (e.g. a multi-line array element) are NOT treated as headers. A header that
# isn't sandbox/agents (triggers, repos, mcp_servers, orchestrator …) turns
# copying off, so those never leak in.
extract_agents_and_sandbox() {
	awk '
		/^[[:space:]]*\[\[?[A-Za-z0-9_.-]+\]\]?[[:space:]]*(#.*)?$/ {
			keep = ($0 ~ /^[[:space:]]*\[sandbox\]/) ||
			       ($0 ~ /^[[:space:]]*\[sandbox\./) ||
			       ($0 ~ /^[[:space:]]*\[agents\]/) ||
			       ($0 ~ /^[[:space:]]*\[agents\./)
		}
		keep { print }
	' "$1"
}

# Escape a value for a TOML basic ("...") string: backslash then double-quote.
toml_escape() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# Read the per-run ownership token embedded in the generated config. It is also
# stored independently in every top-level directory teardown may remove.
config_owner() {
	config_owner_from "$CONFIG_FILE"
}

config_owner_from() {
	config_file="$1"
	[ -f "$config_file" ] && [ ! -L "$config_file" ] || return 1
	line="$(LC_ALL=C sed -n '1p' "$config_file")" || return 1
	prefix="$CONFIG_MARKER"
	suffix=" — safe to delete. Isolated GRAITH_PROFILE=demo."
	case "$line" in
		"$prefix"*"$suffix") ;;
		*) return 1 ;;
	esac
	owner="${line#"$prefix"}"
	owner="${owner%"$suffix"}"
	[ "${#owner}" -eq 32 ] || return 1
	case "$owner" in
		*[!0-9a-f]*) return 1 ;;
	esac
	printf '%s\n' "$owner"
}

config_checksum() {
	LC_ALL=C cksum < "$1"
}

path_exists() {
	[ -e "$1" ] || [ -L "$1" ]
}

directory_owned_by() {
	dir="$1" owner="$2"
	[ -d "$dir" ] && [ ! -L "$dir" ] || return 1
	marker="$dir/$OWNER_FILE"
	[ -f "$marker" ] && [ ! -L "$marker" ] || return 1
	[ "$(cat "$marker")" = "$owner" ]
}

config_directory_owned_by() {
	dir="$1" owner="$2"
	directory_owned_by "$dir" "$owner" || return 1
	[ "$(config_owner_from "$dir/config.toml" || true)" = "$owner" ] || return 1
	proof="$dir/$CONFIG_PROOF_FILE"
	[ -f "$proof" ] && [ ! -L "$proof" ] || return 1
	checksum="$(config_checksum "$dir/config.toml")" || return 1
	[ "$(cat "$proof")" = "$owner $checksum" ]
}

write_config_proof() {
	dir="$1" owner="$2"
	checksum="$(config_checksum "$dir/config.toml")" || return 1
	(umask 077 && printf '%s %s\n' "$owner" "$checksum" > "$dir/$CONFIG_PROOF_FILE")
	config_directory_owned_by "$dir" "$owner"
}

profile_paths_exist() {
	path_exists "$CONFIG_DIR" || path_exists "$DEMO_DATA_DIR" ||
		{ [ -n "$RUNTIME_DIR" ] && path_exists "$RUNTIME_DIR"; }
}

# Runtime state is ephemeral. Once both durable directories independently prove
# the config's token, an absent runtime target is safe to reconstruct. A present
# runtime target must already carry the same proof.
profile_owned_by() {
	owner="$1"
	[ -n "$owner" ] || return 1
	config_directory_owned_by "$CONFIG_DIR" "$owner" || return 1
	directory_owned_by "$DEMO_DATA_DIR" "$owner" || return 1
	if [ -n "$RUNTIME_DIR" ] && path_exists "$RUNTIME_DIR"; then
		directory_owned_by "$RUNTIME_DIR" "$owner" || return 1
	fi
}

create_owned_directory() {
	dir="$1" owner="$2"
	if ! (umask 077 && mkdir "$dir"); then
		echo "refusing: could not exclusively create demo target $dir" >&2
		return 1
	fi
	if ! (umask 077 && printf '%s\n' "$owner" > "$dir/$OWNER_FILE"); then
		echo "refusing: could not establish ownership of demo target $dir" >&2
		return 1
	fi
	directory_owned_by "$dir" "$owner"
}

# Refuse every partially-owned or unowned target before building or invoking
# `gr`. In particular, an absent config cannot authorize existing data/runtime
# state or an already-running daemon.
existing_owner=""
if profile_paths_exist; then
	existing_owner="$(config_owner || true)"
	if ! profile_owned_by "$existing_owner"; then
		echo "refusing: the fixed demo profile has pre-existing state without matching harness ownership markers." >&2
		echo "No config, data, runtime, daemon, or session state was changed. Remove the paths manually" >&2
		echo "only if you intend to hand the GRAITH_PROFILE=demo profile to this harness." >&2
		exit 1
	fi
fi

case "$DEMO_OS" in
	Darwin) DEMO_SANDBOX_BACKEND="${GRAITH_DEMO_SANDBOX_BACKEND:-safehouse}" ;;
	Linux)  DEMO_SANDBOX_BACKEND="${GRAITH_DEMO_SANDBOX_BACKEND:-nono}" ;;
esac

append_default_sandbox() {
	cat >> "$CONFIG_FILE" <<EOF

[sandbox]
enabled = true
backend = "$(toml_escape "$DEMO_SANDBOX_BACKEND")"
EOF
}

# Prefer the freshly-built binary in the repo root; fall back to building it.
GR="$REPO_ROOT/gr"
if [ ! -x "$GR" ]; then
	echo "==> building gr"
	(cd "$REPO_ROOT" && go build -o gr ./cmd/graith)
fi

# Idempotency: clear a previous run only after all of its targets prove the same
# ownership token. Teardown errors are fatal; setup must not adopt what remains.
if [ -n "$existing_owner" ]; then
	echo "==> clearing previous harness-owned demo run"
	"$DEMO_DIR/teardown.sh"
fi

# Establish independent ownership before the daemon can create runtime state.
# Final-component mkdir (rather than mkdir -p) prevents adopting a target that
# appears between the up-front check and creation.
OWNERSHIP_ID="$(LC_ALL=C od -An -N16 -tx1 /dev/urandom | tr -d '[:space:]')"
if [ "${#OWNERSHIP_ID}" -ne 32 ]; then
	echo "refusing: could not generate a demo ownership token" >&2
	exit 1
fi
mkdir -p "$(dirname "$CONFIG_DIR")" "$(dirname "$DEMO_DATA_DIR")"
[ -z "$RUNTIME_DIR" ] || mkdir -p "$(dirname "$RUNTIME_DIR")"
create_owned_directory "$CONFIG_DIR" "$OWNERSHIP_ID"
create_owned_directory "$DEMO_DATA_DIR" "$OWNERSHIP_ID"
[ -z "$RUNTIME_DIR" ] || create_owned_directory "$RUNTIME_DIR" "$OWNERSHIP_ID"

echo "==> writing demo config to $CONFIG_FILE"
(umask 077 && cat > "$CONFIG_FILE" <<EOF
$CONFIG_MARKER$OWNERSHIP_ID — safe to delete. Isolated GRAITH_PROFILE=demo.
allowed_repo_paths = ["$(toml_escape "$DEMO_REPO_PARENT")"]

# All demo runtime state (socket, worktrees, logs, state, messages, tmp) under
# one throwaway dir, so nothing lands in ~/.local/share.
data_dir = "$(toml_escape "$DEMO_DATA_DIR")"

[status_bar]
enabled = true
EOF
)

# Mirror your real setup: copy the [agents.*] and [sandbox]/[sandbox.*] tables
# straight out of your default graith config. Triggers, repos, mcp_servers and
# the orchestrator are deliberately left out.
agents_sandbox=""
if [ -f "$SRC_CONFIG" ]; then
	agents_sandbox="$(extract_agents_and_sandbox "$SRC_CONFIG" || true)"
fi

if [ -n "$agents_sandbox" ]; then
	printf '\n%s\n' "$agents_sandbox" >> "$CONFIG_FILE"
	echo "==> copied agent/sandbox tables from $SRC_CONFIG"

	# Fail LOUD, not silent, about the actual sandbox posture — the demo launches
	# real authenticated agents against a writable repo, so "sandboxed" must be
	# real, not assumed.
	if printf '%s\n' "$agents_sandbox" | grep -qE '^[[:space:]]*\[sandbox\]'; then
		if printf '%s\n' "$agents_sandbox" | grep -qE '^[[:space:]]*enabled[[:space:]]*=[[:space:]]*true'; then
			echo "==> demo agents will run SANDBOXED (copied [sandbox] enabled = true)"
		else
			echo "refusing: copied [sandbox] is not enabled; demo agents may not run unsandboxed." >&2
			exit 1
		fi
	else
		echo "==> no copied [sandbox]; using mandatory $DEMO_SANDBOX_BACKEND sandbox"
		append_default_sandbox
	fi
else
	echo "==> no agent/sandbox config found in $SRC_CONFIG — using secure built-in agent defaults"
	append_default_sandbox
fi

# Bind the config ownership token to the complete generated file. Teardown uses
# this proof to reject a changed data_dir and to create one verified snapshot
# for every subsequent CLI invocation.
if ! write_config_proof "$CONFIG_DIR" "$OWNERSHIP_ID"; then
	echo "refusing: could not bind demo ownership to the generated config" >&2
	exit 1
fi

# Start a fresh daemon that loads the config above. NOTE: don't call
# `gr daemon start` — that's the hidden *foreground* daemon entry point and
# would block here forever. Any normal command auto-starts the daemon in the
# background (via EnsureDaemon) and blocks only until it's ready.
echo "==> starting demo daemon"
"$GR" list >/dev/null 2>&1 || true

# create_session <name> <agent> <summary>
create_session() {
	name="$1" agent="$2" summary="$3"
	echo "==> creating session: $name ($agent)"
	"$GR" new "$name" --repo "$DEMO_REPO" --agent "$agent" --background >/dev/null
	# A short beat so the agent process is up and the status reads running.
	sleep 0.5
	"$GR" status "$name" "$summary" >/dev/null 2>&1 || true
}

create_session tracing-api  claude "Adding tracing ingest endpoint"
create_session trace-ui     codex  "Building the trace export view"
create_session flaky-tests  claude "Hunting a race in handler_test.go"
create_session docs-refresh codex  "Refreshed the triggers docs"

# Leave one session stopped so `gr list` shows a mix of running/stopped.
echo "==> stopping one session (docs-refresh) for a running/stopped mix"
"$GR" stop docs-refresh --force >/dev/null 2>&1 || true

# Star one so the demo can show the starred marker.
"$GR" update tracing-api --starred=true >/dev/null 2>&1 || true

echo
echo "Demo environment ready. Sessions:"
"$GR" list || true
echo
echo "Record with:  make demo        (or: vhs demo/demo.tape)"
echo "Tear down:    make demo-clean  (or: demo/teardown.sh)"
