#!/usr/bin/env bash
#
# setup.sh — stand up an isolated graith environment for the demo recording.
#
# Everything runs under the dedicated, fixed `demo` profile (GRAITH_PROFILE=demo),
# so it never touches your real sessions, config, or data:
#   config: ~/.config/graith-demo/config.toml
#   data:   ~/.graith-demo/   (daemon socket, worktrees, state, logs, messages)
#
# Sessions run your real local agents (claude/codex) with your real sandbox —
# both copied from your default graith config — so the demo is the genuine
# article. They start idle (no prompt); the tape attaches and types prompts to
# show real responses. Re-running is safe — it tears down the previous demo
# state first (ownership-guarded).
#
# NOTE: run this *unsandboxed* on your own machine — it starts a daemon (binds a
# unix socket) and creates git worktrees, which a restrictive agent sandbox
# blocks. (The demo's *agents* are still sandboxed; the recording process is not.)

set -euo pipefail

# Fixed, isolated profile. Clear any ambient graith session/agent env so every
# `gr` call targets the demo profile cleanly: an inherited GRAITH_SESSION_ID
# would retarget `gr status`/parent new sessions, and agent-mode would emit JSON
# that the teardown purge loop can't parse.
export GRAITH_PROFILE=demo
export GR_AGENT_MODE=0
unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
      GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

# The default-profile config we copy [agents.*] and [sandbox] from, so the demo
# runs the exact claude/codex you already have, sandboxed the same way.
SRC_CONFIG="${GRAITH_DEMO_SRC_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/graith/config.toml}"

# Fixed harness-owned paths — never from the environment, so nothing can alias a
# real graith data dir under rm -rf (teardown only rm's when it owns them).
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/graith-demo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
DEMO_DATA_DIR="$HOME/.graith-demo"
CONFIG_MARKER="# Generated by demo/setup.sh"

# The repo the demo sessions "work" on. Safe to override (used only for --repo,
# never for deletion). Its parent is whitelisted in allowed_repo_paths.
DEMO_REPO="${DEMO_REPO:-$REPO_ROOT}"
DEMO_REPO_PARENT="$(cd "$DEMO_REPO/.." && pwd)"

# Print only the [sandbox], [sandbox.*], [agents] and [agents.*] TOML tables
# from $1. Only a well-formed table header ([name] / [[name]], optional trailing
# comment) resets the keep flag — array-continuation lines that start with '['
# (e.g. a multi-line array element) are NOT treated as headers. A header that
# isn't sandbox/agents (triggers, repos, mcp_servers, orchestrator …) turns
# copying off, so those never leak in.
extract_agents_and_sandbox() {
	awk '
		/^[[:space:]]*\[\[?[A-Za-z0-9_.-]+\]\]?[[:space:]]*(#.*)?$/ {
			keep = ($0 ~ /^[[:space:]]*\[sandbox\]/) ||
			       ($0 ~ /^[[:space:]]*\[sandbox\./) ||
			       ($0 ~ /^[[:space:]]*\[agents\]/) ||
			       ($0 ~ /^[[:space:]]*\[agents\./)
		}
		keep { print }
	' "$1"
}

# Escape a value for a TOML basic ("...") string: backslash then double-quote.
toml_escape() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# Prefer the freshly-built binary in the repo root; fall back to building it.
GR="$REPO_ROOT/gr"
if [ ! -x "$GR" ]; then
	echo "==> building gr"
	(cd "$REPO_ROOT" && go build -o gr ./cmd/graith)
fi

# Safety: never overwrite/purge a `demo` profile this harness didn't create.
if [ -e "$CONFIG_FILE" ] && ! head -n 1 "$CONFIG_FILE" | grep -q "Generated by demo/setup.sh"; then
	echo "refusing: $CONFIG_FILE already exists and was not created by this demo harness." >&2
	echo "The demo uses a fixed GRAITH_PROFILE=demo. Remove that config (and ~/.graith-demo)" >&2
	echo "to hand the 'demo' profile to the harness." >&2
	exit 1
fi

# Idempotency: clear any previous harness run first (teardown is ownership-guarded).
echo "==> clearing any previous demo run"
"$DEMO_DIR/teardown.sh" >/dev/null 2>&1 || true

echo "==> writing demo config to $CONFIG_FILE"
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
$CONFIG_MARKER — safe to delete. Isolated GRAITH_PROFILE=demo.
allowed_repo_paths = ["$(toml_escape "$DEMO_REPO_PARENT")"]

# All demo runtime state (socket, worktrees, logs, state, messages, tmp) under
# one throwaway dir, so nothing lands in ~/.local/share.
data_dir = "$(toml_escape "$DEMO_DATA_DIR")"

[status_bar]
enabled = true
EOF

# Mirror your real setup: copy the [agents.*] and [sandbox]/[sandbox.*] tables
# straight out of your default graith config. Triggers, repos, mcp_servers and
# the orchestrator are deliberately left out.
agents_sandbox=""
if [ -f "$SRC_CONFIG" ]; then
	agents_sandbox="$(extract_agents_and_sandbox "$SRC_CONFIG" || true)"
fi

if [ -n "$agents_sandbox" ]; then
	printf '\n%s\n' "$agents_sandbox" >> "$CONFIG_FILE"
	echo "==> copied agent/sandbox tables from $SRC_CONFIG"

	# Fail LOUD, not silent, about the actual sandbox posture — the demo launches
	# real authenticated agents against a writable repo, so "sandboxed" must be
	# real, not assumed.
	if printf '%s\n' "$agents_sandbox" | grep -qE '^[[:space:]]*\[sandbox\]'; then
		if printf '%s\n' "$agents_sandbox" | grep -qE '^[[:space:]]*enabled[[:space:]]*=[[:space:]]*true'; then
			echo "==> demo agents will run SANDBOXED (copied [sandbox] enabled = true)"
		else
			echo "!! WARNING: copied [sandbox] is present but NOT enabled — demo agents run UNSANDBOXED" >&2
		fi
	else
		echo "!! WARNING: no [sandbox] table in $SRC_CONFIG — demo agents run UNSANDBOXED" >&2
	fi
else
	echo "!! WARNING: no agent/sandbox config found in $SRC_CONFIG — using unsandboxed claude/codex" >&2
	cat >> "$CONFIG_FILE" <<'FALLBACK'

[sandbox]
enabled = false

[agents.claude]
command = "claude"
args = ["--dangerously-skip-permissions", "--session-id", "{agent_session_id}"]

[agents.codex]
command = "codex"
args = ["--dangerously-bypass-approvals-and-sandbox"]
FALLBACK
fi

# Start a fresh daemon that loads the config above. NOTE: don't call
# `gr daemon start` — that's the hidden *foreground* daemon entry point and
# would block here forever. Any normal command auto-starts the daemon in the
# background (via EnsureDaemon) and blocks only until it's ready.
echo "==> starting demo daemon"
"$GR" list >/dev/null 2>&1 || true

# create_session <name> <agent> <summary>
create_session() {
	name="$1" agent="$2" summary="$3"
	echo "==> creating session: $name ($agent)"
	"$GR" new "$name" --repo "$DEMO_REPO" --agent "$agent" --background >/dev/null
	# A short beat so the agent process is up and the status reads running.
	sleep 0.5
	"$GR" status "$name" "$summary" >/dev/null 2>&1 || true
}

create_session tracing-api  claude "Adding tracing ingest endpoint"
create_session trace-ui     codex  "Building the trace export view"
create_session flaky-tests  claude "Hunting a race in handler_test.go"
create_session docs-refresh codex  "Refreshed the triggers docs"

# Leave one session stopped so `gr list` shows a mix of running/stopped.
echo "==> stopping one session (docs-refresh) for a running/stopped mix"
"$GR" stop docs-refresh --force >/dev/null 2>&1 || true

# Star one so the demo can show the starred marker.
"$GR" star tracing-api >/dev/null 2>&1 || true

echo
echo "Demo environment ready. Sessions:"
"$GR" list || true
echo
echo "Record with:  make demo        (or: vhs demo/demo.tape)"
echo "Tear down:    make demo-clean  (or: demo/teardown.sh)"
