#!/usr/bin/env bash
#
# teardown.sh — remove the isolated graith demo environment created by setup.sh.
#
# Safety: this only ever acts on the fixed, harness-owned `demo` profile, and
# only when the config, data, and (when present) runtime directories carry the
# same per-run ownership token. A missing runtime directory is reconstructible
# because it is ephemeral; every present target must already be owned before
# teardown contacts a daemon or purges a session.

set -euo pipefail

# Fixed, isolated profile. Clear any ambient graith session/agent env so every
# `gr` call targets the demo profile cleanly: an inherited GRAITH_SESSION_ID
# would retarget `gr status`, and agent-mode would turn `gr list -q` into a JSON
# array the purge loop below can't parse.
export GRAITH_PROFILE=demo
export GR_AGENT_MODE=0
unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
      GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

# Fixed harness-owned paths — never from the environment.
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/graith-demo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
DATA_DIR="$HOME/.graith-demo"
RUNTIME_DIR="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/graith-demo}"
OWNER_FILE=".graith-demo-owner"
CONFIG_MARKER="# Generated by demo/setup.sh owner="

GR="$REPO_ROOT/gr"
if [ ! -x "$GR" ]; then
	GR="$(command -v gr 2>/dev/null || true)"
fi

# Only our generated config carries a valid ownership token on line 1.
config_owner() {
	[ -f "$CONFIG_FILE" ] && [ ! -L "$CONFIG_FILE" ] || return 1
	line="$(LC_ALL=C sed -n '1p' "$CONFIG_FILE")" || return 1
	prefix="$CONFIG_MARKER"
	suffix=" — safe to delete. Isolated GRAITH_PROFILE=demo."
	case "$line" in
		"$prefix"*"$suffix") ;;
		*) return 1 ;;
	esac
	owner="${line#"$prefix"}"
	owner="${owner%"$suffix"}"
	[ "${#owner}" -eq 32 ] || return 1
	case "$owner" in
		*[!0-9a-f]*) return 1 ;;
	esac
	printf '%s\n' "$owner"
}

path_exists() {
	[ -e "$1" ] || [ -L "$1" ]
}

directory_owned_by() {
	dir="$1" owner="$2"
	[ -d "$dir" ] && [ ! -L "$dir" ] || return 1
	marker="$dir/$OWNER_FILE"
	[ -f "$marker" ] && [ ! -L "$marker" ] || return 1
	[ "$(cat "$marker")" = "$owner" ]
}

profile_paths_exist() {
	path_exists "$CONFIG_DIR" || path_exists "$DATA_DIR" ||
		{ [ -n "$RUNTIME_DIR" ] && path_exists "$RUNTIME_DIR"; }
}

durable_profile_owned_by() {
	owner="$1"
	[ -n "$owner" ] || return 1
	directory_owned_by "$CONFIG_DIR" "$owner" || return 1
	directory_owned_by "$DATA_DIR" "$owner"
}

profile_owned_by() {
	owner="$1"
	durable_profile_owned_by "$owner" || return 1
	if [ -n "$RUNTIME_DIR" ] && path_exists "$RUNTIME_DIR"; then
		directory_owned_by "$RUNTIME_DIR" "$owner" || return 1
	fi
}

profile_fully_owned_by() {
	owner="$1"
	durable_profile_owned_by "$owner" || return 1
	[ -z "$RUNTIME_DIR" ] || directory_owned_by "$RUNTIME_DIR" "$owner"
}

if ! profile_paths_exist; then
	echo "No demo environment to remove."
	exit 0
fi

owner="$(config_owner || true)"
if ! profile_owned_by "$owner"; then
	echo "refusing: demo profile state is not fully owned by this harness; leaving every target untouched." >&2
	exit 1
fi

if [ -z "$GR" ]; then
	echo "refusing to remove demo state: gr not found, so a demo daemon cannot be stopped safely" >&2
	exit 1
fi

# A real `gr list` creates the ephemeral runtime directory without a harness
# marker. Re-establish it after durable authorization but before any `gr` call.
# Atomic final-component mkdir refuses a concurrently-created unowned target.
if [ -n "$RUNTIME_DIR" ] && ! path_exists "$RUNTIME_DIR"; then
	mkdir -p "$(dirname "$RUNTIME_DIR")"
	if (umask 077 && mkdir "$RUNTIME_DIR"); then
		if ! (umask 077 && printf '%s\n' "$owner" > "$RUNTIME_DIR/$OWNER_FILE"); then
			echo "refusing to remove demo state: could not mark reconstructed runtime state" >&2
			exit 1
		fi
	elif ! directory_owned_by "$RUNTIME_DIR" "$owner"; then
		echo "refusing to remove demo state: runtime state appeared without matching ownership" >&2
		exit 1
	fi
fi
if ! profile_fully_owned_by "$owner"; then
	echo "refusing to remove demo state: ownership changed before daemon access" >&2
	exit 1
fi

# Enumerate live and soft-deleted sessions before the first purge. Any list
# failure or marker mismatch therefore refuses while all sessions are intact.
if ! active_sessions="$("$GR" list -q 2>/dev/null)"; then
	echo "refusing to remove demo state: could not enumerate live sessions" >&2
	exit 1
fi
if ! deleted_sessions="$("$GR" list --deleted -q 2>/dev/null)"; then
	echo "refusing to remove demo state: could not enumerate deleted sessions" >&2
	exit 1
fi
if ! profile_fully_owned_by "$owner"; then
	echo "refusing to remove demo state: ownership changed before session purge" >&2
	exit 1
fi

# Purge every known demo session so its worktree and branch are removed cleanly.
# -y/-f skip confirmations; `while read` works on macOS bash 3.2.
for sessions in "$active_sessions" "$deleted_sessions"; do
	while IFS= read -r session; do
		[ -z "$session" ] && continue
		echo "==> purging session: $session"
		if ! "$GR" purge "$session" -y -f >/dev/null 2>&1; then
			echo "refusing to remove demo state: purge failed for $session" >&2
			exit 1
		fi
	done <<< "$sessions"
done

echo "==> stopping demo daemon"
if ! "$GR" daemon stop >/dev/null 2>&1; then
	echo "refusing to remove demo state: daemon stop failed" >&2
	exit 1
fi

# Markers authorize each recursive removal independently. Check once more at
# the destructive boundary in case anything changed while the daemon stopped.
if ! profile_fully_owned_by "$owner"; then
	echo "refusing to remove demo state: ownership changed before directory removal" >&2
	exit 1
fi

echo "==> removing $CONFIG_DIR and $DATA_DIR"
rm -rf "$CONFIG_DIR" "$DATA_DIR"
[ -n "$RUNTIME_DIR" ] && rm -rf "$RUNTIME_DIR"

echo "Demo environment removed."
