#!/usr/bin/env bash
#
# teardown.sh — remove the isolated graith demo environment created by setup.sh.
#
# Safety: this only ever acts on the fixed, harness-owned `demo` profile, and
# only when it can confirm ownership via the marker line setup.sh writes as the
# first line of the generated config. If a ~/.config/graith-demo config exists
# that this harness did NOT create, teardown refuses to touch it — `demo` is a
# perfectly valid profile name someone else could be using. All paths are fixed
# (never taken from the environment), so nothing can alias a real graith data
# dir under `rm -rf`.

set -euo pipefail

# Fixed, isolated profile. Clear any ambient graith session/agent env so every
# `gr` call targets the demo profile cleanly: an inherited GRAITH_SESSION_ID
# would retarget `gr status`, and agent-mode would turn `gr list -q` into a JSON
# array the purge loop below can't parse.
export GRAITH_PROFILE=demo
export GR_AGENT_MODE=0
unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
      GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

# Fixed harness-owned paths — never from the environment.
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/graith-demo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
DATA_DIR="$HOME/.graith-demo"
RUNTIME_DIR="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/graith-demo}"

GR="$REPO_ROOT/gr"
if [ ! -x "$GR" ]; then
	GR="$(command -v gr 2>/dev/null || true)"
fi

# Only our generated config carries this marker on line 1.
harness_owned() {
	[ -f "$CONFIG_FILE" ] && head -n 1 "$CONFIG_FILE" | grep -q "Generated by demo/setup.sh"
}

if ! harness_owned; then
	if [ -e "$CONFIG_FILE" ]; then
		echo "refusing to remove $CONFIG_DIR: it exists but was not created by this demo" >&2
		echo "harness. If it's yours it stays untouched; remove it manually to reclaim the" >&2
		echo "'demo' profile for the harness." >&2
	else
		echo "No demo environment to remove."
	fi
	exit 0
fi

# Owned. Purge every demo session — live AND soft-deleted — so their worktrees
# and branches are removed cleanly (not just orphaned when the data dir goes).
# -y/-f skip confirmations; `while read` (not mapfile) works on macOS bash 3.2.
# Capture lists first (|| true) so a `gr list` failure can't trip pipefail.
if [ -n "$GR" ]; then
	for flag in "" "--deleted"; do
		sessions="$("$GR" list $flag -q 2>/dev/null || true)"
		printf '%s\n' "$sessions" | while IFS= read -r s; do
			[ -z "$s" ] && continue
			echo "==> purging session: $s"
			"$GR" purge "$s" -y -f >/dev/null 2>&1 || true
		done
	done
	echo "==> stopping demo daemon"
	"$GR" daemon stop >/dev/null 2>&1 || true
else
	echo "!! gr not found — skipping session purge, removing harness dirs only" >&2
fi

echo "==> removing $CONFIG_DIR and $DATA_DIR"
rm -rf "$CONFIG_DIR" "$DATA_DIR"
[ -n "$RUNTIME_DIR" ] && rm -rf "$RUNTIME_DIR"

echo "Demo environment removed."
