#!/usr/bin/env bash
#
# teardown.sh — remove the isolated graith demo environment created by setup.sh.
#
# Safety: this only ever acts on the fixed, harness-owned `demo` profile, and
# only when the config, data, and runtime directories independently carry the
# same ownership token. If any fixed target is absent, unmarked, mismatched, or
# a symlink, teardown refuses before contacting a daemon — `demo` is a perfectly
# valid profile name someone else could be using.

set -euo pipefail

# Fixed, isolated profile. Clear any ambient graith session/agent env so every
# `gr` call targets the demo profile cleanly: an inherited GRAITH_SESSION_ID
# would retarget `gr status`, and agent-mode would turn `gr list -q` into a JSON
# array the purge loop below can't parse.
export GRAITH_PROFILE=demo
export GR_AGENT_MODE=0
unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
      GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

# Fixed harness-owned paths — never from the environment.
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/graith-demo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
DATA_DIR="$HOME/.graith-demo"
RUNTIME_DIR="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/graith-demo}"
OWNER_FILE=".graith-demo-owner"

GR="$REPO_ROOT/gr"
if [ ! -x "$GR" ]; then
	GR="$(command -v gr 2>/dev/null || true)"
fi

# Only our generated config carries an owner token on line 1.
config_owner() {
	[ -f "$CONFIG_FILE" ] && [ ! -L "$CONFIG_FILE" ] || return 1
	sed -n '1s/^# Generated by demo\/setup.sh owner=\([^ ]*\).*/\1/p' "$CONFIG_FILE"
}

directory_owned_by() {
	dir="$1" owner="$2"
	[ -d "$dir" ] && [ ! -L "$dir" ] || return 1
	[ -f "$dir/$OWNER_FILE" ] && [ ! -L "$dir/$OWNER_FILE" ] || return 1
	[ "$(cat "$dir/$OWNER_FILE")" = "$owner" ]
}

profile_paths_exist() {
	[ -e "$CONFIG_DIR" ] || [ -L "$CONFIG_DIR" ] ||
		[ -e "$DATA_DIR" ] || [ -L "$DATA_DIR" ] ||
		{ [ -n "$RUNTIME_DIR" ] && { [ -e "$RUNTIME_DIR" ] || [ -L "$RUNTIME_DIR" ]; }; }
}

profile_owned_by() {
	owner="$1"
	[ -n "$owner" ] || return 1
	directory_owned_by "$CONFIG_DIR" "$owner" || return 1
	directory_owned_by "$DATA_DIR" "$owner" || return 1
	if [ -n "$RUNTIME_DIR" ]; then
		directory_owned_by "$RUNTIME_DIR" "$owner" || return 1
	fi
}

if ! profile_paths_exist; then
	echo "No demo environment to remove."
	exit 0
fi

owner="$(config_owner || true)"
if ! profile_owned_by "$owner"; then
	echo "refusing: demo profile state is not fully owned by this harness; leaving every target untouched." >&2
	exit 1
fi

# Owned. Purge every demo session — live AND soft-deleted — so their worktrees
# and branches are removed cleanly (not just orphaned when the data dir goes).
# -y/-f skip confirmations; `while read` (not mapfile) works on macOS bash 3.2.
# Capture lists first and stop on uncertainty: deleting state after a failed
# list/purge could strand live processes or worktrees outside the data dir.
if [ -n "$GR" ]; then
	for flag in "" "--deleted"; do
		if ! sessions="$("$GR" list $flag -q 2>/dev/null)"; then
			echo "refusing to remove demo state: could not enumerate $flag sessions" >&2
			exit 1
		fi
		while IFS= read -r s; do
			[ -z "$s" ] && continue
			echo "==> purging session: $s"
			if ! "$GR" purge "$s" -y -f >/dev/null 2>&1; then
				echo "refusing to remove demo state: purge failed for $s" >&2
				exit 1
			fi
		done <<< "$sessions"
	done
	echo "==> stopping demo daemon"
	if ! "$GR" daemon stop >/dev/null 2>&1; then
		echo "refusing to remove demo state: daemon stop failed" >&2
		exit 1
	fi
else
	echo "refusing to remove demo state: gr not found, so daemon ownership cannot be checked" >&2
	exit 1
fi

# Re-check the markers after daemon work and immediately before deletion.
if ! profile_owned_by "$owner"; then
	echo "refusing to remove demo state: ownership changed during teardown" >&2
	exit 1
fi

echo "==> removing $CONFIG_DIR and $DATA_DIR"
rm -rf "$CONFIG_DIR" "$DATA_DIR"
[ -n "$RUNTIME_DIR" ] && rm -rf "$RUNTIME_DIR"

echo "Demo environment removed."
