#!/usr/bin/env bash

set -euo pipefail

DEMO_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_SOURCE/.." && pwd)"
# Keep the Unix-socket path comfortably below the macOS sockaddr_un limit even
# when the caller's TMPDIR is a deeply nested graith worktree path.
TEST_ROOT="$(mktemp -d "/tmp/graith-demo-test.XXXXXX")"
REAL_GR="$TEST_ROOT/gr-real"
REAL_FIXTURES="$TEST_ROOT/real-fixtures"
OWNER_A="baddcafebaddcafebaddcafebaddcafe"
OWNER_B="decafbaddecafbaddecafbaddecafbad"
SESSION_A="baddcafe"
SESSION_B="decafbad"

fail() {
	echo "FAIL: $*" >&2
	exit 1
}

run_real_gr() {
	fixture="$1"
	shift
	(
		export HOME="$fixture/home"
		export XDG_CONFIG_HOME="$fixture/config"
		export XDG_RUNTIME_DIR="$fixture/runtime"
		export GRAITH_PROFILE=demo
		export GR_AGENT_MODE=0
		unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
			GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true
		"$REAL_GR" "$@"
	)
}

cleanup() {
	status=$?
	trap - EXIT INT TERM
	set +e
	if [ -f "$REAL_FIXTURES" ] && [ -x "$REAL_GR" ]; then
		while IFS= read -r fixture; do
			[ -z "$fixture" ] || run_real_gr "$fixture" daemon stop >/dev/null 2>&1
		done < "$REAL_FIXTURES"
	fi
	rm -rf "$TEST_ROOT"
	exit "$status"
}
trap cleanup EXIT INT TERM

new_fixture_base() {
	name="$1"
	fixture="$TEST_ROOT/$name"
	mkdir -p "$fixture/repo/demo" "$fixture/home" "$fixture/config" "$fixture/runtime"
	cp "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$fixture/repo/demo/"
	chmod +x "$fixture/repo/demo/setup.sh" "$fixture/repo/demo/teardown.sh"
	: > "$fixture/gr.log"
}

new_fake_fixture() {
	new_fixture_base "$1"
	cat > "$fixture/repo/gr" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${GRAITH_DEMO_TEST_GR_LOG:?}"
if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
	mkdir -p "$XDG_RUNTIME_DIR/graith-demo"
fi
case "${1:-}" in
	--config) shift 2 ;;
esac
case "${1:-}" in
	list)
		deleted=false
		json=false
		for arg in "$@"; do
			[ "$arg" != "--deleted" ] || deleted=true
			[ "$arg" != "--json" ] || json=true
		done
		if $deleted; then
			[ "${GRAITH_DEMO_TEST_DELETED_LIST_STATUS:-0}" -eq 0 ] || exit "$GRAITH_DEMO_TEST_DELETED_LIST_STATUS"
			sessions="${GRAITH_DEMO_TEST_DELETED_SESSIONS:-}"
		else
			[ "${GRAITH_DEMO_TEST_LIST_STATUS:-0}" -eq 0 ] || exit "$GRAITH_DEMO_TEST_LIST_STATUS"
			sessions="${GRAITH_DEMO_TEST_ACTIVE_SESSIONS:-}"
		fi
		if $json; then
			if [ -n "$sessions" ]; then
				printf '["%s"]\n' "$(printf '%s' "$sessions" | sed 's/,/","/g')"
			else
				printf '[]\n'
			fi
		elif [ -n "$sessions" ]; then
			printf '%s\n' "$sessions" | tr ',' '\n'
		fi
		;;
	purge) exit "${GRAITH_DEMO_TEST_PURGE_STATUS:-0}" ;;
	daemon) exit "${GRAITH_DEMO_TEST_STOP_STATUS:-0}" ;;
esac
exit 0
EOF
	chmod +x "$fixture/repo/gr"
}

new_real_fixture() {
	new_fixture_base "$1"
	cat > "$fixture/repo/gr" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${GRAITH_DEMO_TEST_GR_LOG:?}"
case "${1:-}" in
	--config)
		config_file="$2"
		shift 2
		case "${1:-}" in
			list|daemon) exec "${GRAITH_DEMO_REAL_GR:?}" --config "$config_file" "$@" ;;
		esac
		;;
	list|daemon) exec "${GRAITH_DEMO_REAL_GR:?}" "$@" ;;
	*) exit 0 ;;
esac
EOF
	chmod +x "$fixture/repo/gr"
	printf '%s\n' "$fixture" >> "$REAL_FIXTURES"
}

run_setup() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		GRAITH_DEMO_SRC_CONFIG="$fixture/missing-config.toml" "$fixture/repo/demo/setup.sh"
}

run_teardown() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		"$fixture/repo/demo/teardown.sh"
}

run_setup_without_runtime() {
	fixture="$1"
	env -u XDG_RUNTIME_DIR HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		GRAITH_DEMO_SRC_CONFIG="$fixture/missing-config.toml" "$fixture/repo/demo/setup.sh"
}

run_teardown_without_runtime() {
	fixture="$1"
	env -u XDG_RUNTIME_DIR HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		"$fixture/repo/demo/teardown.sh"
}

write_owned_profile() {
	fixture="$1" owner="$2" runtime="${3:-present}"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir"
	[ "$runtime" != "present" ] || mkdir -p "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=%s — safe to delete. Isolated GRAITH_PROFILE=demo.\n' "$owner" > "$config_dir/config.toml"
	printf 'data_dir = "%s"\n' "$data_dir" >> "$config_dir/config.toml"
	printf '%s\n' "$owner" > "$config_dir/.graith-demo-owner"
	printf '%s\n' "$owner" > "$data_dir/.graith-demo-owner"
	# Simulate installer/bootstrap human authority; a clean session must not
	# mint lifecycle authority merely by clearing its environment.
	printf 'demo-human-token-%s\n' "$owner" > "$data_dir/human.token"
	chmod 0600 "$data_dir/human.token"
	[ "$runtime" != "present" ] || printf '%s\n' "$owner" > "$runtime_dir/.graith-demo-owner"
	printf '%s %s\n' "$owner" "$(LC_ALL=C cksum < "$config_dir/config.toml")" > "$config_dir/.graith-demo-config-proof"
}

write_unowned_config() {
	fixture="$1"
	config_dir="$fixture/config/graith-demo"
	mkdir -p "$config_dir"
	printf '# pre-existing user config\ndata_dir = "%s"\n' "$fixture/home/.graith-demo" > "$config_dir/config.toml"
}

assert_sentinels() {
	fixture="$1"
	[ "$(cat "$fixture/config/graith-demo/config-sentinel")" = "canny" ] || fail "config sentinel changed"
	[ "$(cat "$fixture/home/.graith-demo/data-sentinel")" = "dreich" ] || fail "data sentinel changed"
	[ "$(cat "$fixture/runtime/graith-demo/runtime-sentinel")" = "thrawn" ] || fail "runtime sentinel changed"
}

add_sentinels() {
	fixture="$1"
	printf 'canny\n' > "$fixture/config/graith-demo/config-sentinel"
	printf 'dreich\n' > "$fixture/home/.graith-demo/data-sentinel"
	printf 'thrawn\n' > "$fixture/runtime/graith-demo/runtime-sentinel"
}

assert_refuses_setup_target() {
	target="$1"
	new_fake_fixture "setup-$target"
	case "$target" in
		config) sentinel="$fixture/config/graith-demo/sentinel" ;;
		data) sentinel="$fixture/home/.graith-demo/sentinel" ;;
		runtime) sentinel="$fixture/runtime/graith-demo/sentinel" ;;
	esac
	mkdir -p "$(dirname "$sentinel")"
	printf 'canny\n' > "$sentinel"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted pre-existing $target state"
	fi
	[ "$(cat "$sentinel")" = "canny" ] || fail "setup changed pre-existing $target state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for unowned $target state"
}

assert_refuses_teardown_mismatch() {
	target="$1"
	new_fake_fixture "teardown-$target-mismatch"
	write_owned_profile "$fixture" "$OWNER_A"
	add_sentinels "$fixture"
	case "$target" in
		config) printf '%s\n' "$OWNER_B" > "$fixture/config/graith-demo/.graith-demo-owner" ;;
		data) printf '%s\n' "$OWNER_B" > "$fixture/home/.graith-demo/.graith-demo-owner" ;;
		runtime) printf '%s\n' "$OWNER_B" > "$fixture/runtime/graith-demo/.graith-demo-owner" ;;
	esac
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted mismatched $target ownership"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] || fail "teardown contacted gr before refusing $target ownership"
}

assert_owned_teardown_is_idempotent() {
	new_fake_fixture "teardown-owned"
	write_owned_profile "$fixture" "$OWNER_A"
	GRAITH_DEMO_TEST_ACTIVE_SESSIONS="$SESSION_A" \
		GRAITH_DEMO_TEST_DELETED_SESSIONS="$SESSION_B" run_teardown "$fixture" >/dev/null
	grep -q " purge $SESSION_A -y -f$" "$fixture/gr.log" || fail "teardown did not purge a live session by ID"
	grep -q " purge $SESSION_B -y -f$" "$fixture/gr.log" || fail "teardown did not purge a deleted session by ID"
	[ ! -e "$fixture/config/graith-demo" ] &&
		[ ! -e "$fixture/home/.graith-demo" ] &&
		[ ! -e "$fixture/runtime/graith-demo" ] ||
		fail "owned teardown left profile directories"
	run_teardown "$fixture" >/dev/null
}

assert_refuses_on_active_list_failure() {
	new_fake_fixture "teardown-active-list-failure"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_LIST_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored live-session enumeration failure"
	fi
	grep -q ' list -q --json$' "$fixture/gr.log" || fail "teardown did not attempt live-session enumeration"
	if grep -q ' purge ' "$fixture/gr.log"; then
		fail "teardown purged after live-session enumeration failed"
	fi
	[ -d "$fixture/config/graith-demo" ] &&
		[ -d "$fixture/home/.graith-demo" ] &&
		[ -d "$fixture/runtime/graith-demo" ] ||
		fail "teardown removed state after live-session enumeration failed"
}

assert_refuses_before_any_purge() {
	new_fake_fixture "teardown-list-failure"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_ACTIVE_SESSIONS="$SESSION_A" \
		GRAITH_DEMO_TEST_DELETED_LIST_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored deleted-session enumeration failure"
	fi
	grep -q ' list -q --json$' "$fixture/gr.log" || fail "teardown did not enumerate live sessions"
	grep -q ' list --deleted -q --json$' "$fixture/gr.log" || fail "teardown did not enumerate deleted sessions"
	if grep -q ' purge ' "$fixture/gr.log"; then
		fail "teardown purged before all refusal decisions completed"
	fi
	[ -d "$fixture/config/graith-demo" ] &&
		[ -d "$fixture/home/.graith-demo" ] &&
		[ -d "$fixture/runtime/graith-demo" ] ||
		fail "teardown removed state after pre-purge refusal"

	new_fake_fixture "teardown-invalid-deleted-id"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_ACTIVE_SESSIONS="$SESSION_A" \
		GRAITH_DEMO_TEST_DELETED_SESSIONS="croft" run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted an invalid deleted-session enumeration"
	fi
	if grep -q ' purge ' "$fixture/gr.log"; then
		fail "teardown purged before validating every listed session ID"
	fi
}

assert_refuses_after_purge_or_stop_failure() {
	new_fake_fixture "teardown-purge-failure"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_ACTIVE_SESSIONS="$SESSION_A" \
		GRAITH_DEMO_TEST_PURGE_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored purge failure"
	fi
	grep -q " purge $SESSION_A -y -f$" "$fixture/gr.log" || fail "teardown did not attempt the failing purge"
	if grep -q ' daemon stop$' "$fixture/gr.log"; then
		fail "teardown stopped the daemon after purge failed"
	fi
	[ -d "$fixture/config/graith-demo" ] &&
		[ -d "$fixture/home/.graith-demo" ] &&
		[ -d "$fixture/runtime/graith-demo" ] ||
		fail "teardown removed state after purge failed"

	new_fake_fixture "teardown-stop-failure"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_STOP_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored daemon-stop failure"
	fi
	grep -q ' daemon stop$' "$fixture/gr.log" || fail "teardown did not attempt to stop the daemon"
	[ -d "$fixture/config/graith-demo" ] &&
		[ -d "$fixture/home/.graith-demo" ] &&
		[ -d "$fixture/runtime/graith-demo" ] ||
		fail "teardown removed state after daemon stop failed"
}

assert_setup_reruns_after_runtime_cleanup() {
	new_fake_fixture "setup-rerun"
	run_setup "$fixture" >/dev/null 2>&1 || fail "first setup failed"
	first_owner="$(cat "$fixture/config/graith-demo/.graith-demo-owner")"
	rm -rf "$fixture/runtime/graith-demo"
	[ -f "$fixture/config/graith-demo/.graith-demo-owner" ] || fail "config ownership marker lost"
	[ -f "$fixture/home/.graith-demo/.graith-demo-owner" ] || fail "data ownership marker lost"
	run_setup "$fixture" >/dev/null 2>&1 ||
		fail "setup refused an owned profile after runtime cleanup"
	[ -f "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "rerun did not reconstruct runtime ownership"
	[ "$(cat "$fixture/config/graith-demo/.graith-demo-owner")" != "$first_owner" ] ||
		fail "rerun did not rotate the ownership token"
}

assert_refuses_present_runtime_mismatch() {
	new_fake_fixture "setup-runtime-mismatch"
	write_owned_profile "$fixture" "$OWNER_A"
	printf '%s\n' "$OWNER_B" > "$fixture/runtime/graith-demo/.graith-demo-owner"
	printf 'dreich\n' > "$fixture/runtime/graith-demo/sentinel"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup adopted a present mismatched runtime target"
	fi
	[ "$(cat "$fixture/runtime/graith-demo/sentinel")" = "dreich" ] ||
		fail "setup changed mismatched runtime state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for mismatched runtime state"
}

assert_refuses_rebound_config() {
	new_fake_fixture "teardown-rebound-config"
	write_owned_profile "$fixture" "$OWNER_A"
	unrelated="$fixture/home/unrelated-graith-data"
	mkdir -p "$unrelated"
	printf 'canny\n' > "$unrelated/sentinel"
	printf '%s\n' "# Generated by demo/setup.sh owner=$OWNER_A — safe to delete. Isolated GRAITH_PROFILE=demo." > "$fixture/config/graith-demo/config.toml"
	printf 'data_dir = "%s"\n' "$unrelated" >> "$fixture/config/graith-demo/config.toml"
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted a config rebound to unrelated data"
	fi
	[ "$(cat "$unrelated/sentinel")" = "canny" ] || fail "teardown changed rebound data"
	[ ! -s "$fixture/gr.log" ] || fail "teardown contacted gr for rebound config"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted a config rebound to unrelated data"
	fi
	[ "$(cat "$unrelated/sentinel")" = "canny" ] || fail "setup changed rebound data"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for rebound config"
}

assert_refuses_untracked_runtime_fallback() {
	new_fake_fixture "unset-runtime-setup"
	mkdir -p "$fixture/bin"
	cat > "$fixture/bin/uname" <<'EOF'
#!/usr/bin/env bash
printf 'Linux\n'
EOF
	chmod +x "$fixture/bin/uname"
	if PATH="$fixture/bin:$PATH" run_setup_without_runtime "$fixture" >/dev/null 2>&1; then
		fail "Linux setup accepted an unset XDG_RUNTIME_DIR"
	fi
	[ ! -e "$fixture/config/graith-demo" ] || fail "unset-runtime setup created config state"
	[ ! -e "$fixture/home/.graith-demo" ] || fail "unset-runtime setup created data state"
	[ ! -s "$fixture/gr.log" ] || fail "unset-runtime setup contacted gr"

	new_fake_fixture "unset-runtime-teardown"
	write_owned_profile "$fixture" "$OWNER_A"
	add_sentinels "$fixture"
	mkdir -p "$fixture/bin"
	cp "$TEST_ROOT/unset-runtime-setup/bin/uname" "$fixture/bin/uname"
	if PATH="$fixture/bin:$PATH" run_teardown_without_runtime "$fixture" >/dev/null 2>&1; then
		fail "Linux teardown accepted an unset XDG_RUNTIME_DIR"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] || fail "unset-runtime teardown contacted gr"

	new_fake_fixture "darwin-custom-data-unset-runtime-setup"
	mkdir -p "$fixture/bin"
	cat > "$fixture/bin/uname" <<'EOF'
#!/usr/bin/env bash
printf 'Darwin\n'
EOF
	chmod +x "$fixture/bin/uname"
	if XDG_DATA_HOME="$fixture/custom-data" PATH="$fixture/bin:$PATH" \
		run_setup_without_runtime "$fixture" >/dev/null 2>&1; then
		fail "macOS setup accepted custom XDG data with an unset runtime"
	fi
	[ ! -e "$fixture/config/graith-demo" ] || fail "macOS unset-runtime setup created config state"
	[ ! -e "$fixture/home/.graith-demo" ] || fail "macOS unset-runtime setup created data state"
	[ ! -s "$fixture/gr.log" ] || fail "macOS unset-runtime setup contacted gr"

	new_fake_fixture "darwin-custom-data-unset-runtime-teardown"
	write_owned_profile "$fixture" "$OWNER_A"
	add_sentinels "$fixture"
	mkdir -p "$fixture/bin"
	cp "$TEST_ROOT/darwin-custom-data-unset-runtime-setup/bin/uname" "$fixture/bin/uname"
	if XDG_DATA_HOME="$fixture/custom-data" PATH="$fixture/bin:$PATH" \
		run_teardown_without_runtime "$fixture" >/dev/null 2>&1; then
		fail "macOS teardown accepted custom XDG data with an unset runtime"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] || fail "macOS unset-runtime teardown contacted gr"
}

assert_replacement_at_remove_boundary_is_preserved() {
	new_fake_fixture "teardown-remove-race"
	write_owned_profile "$fixture" "$OWNER_A"
	mkdir -p "$fixture/bin"
	cat > "$fixture/bin/mv" <<'EOF'
#!/usr/bin/env bash
/bin/mv "$@" || exit
if [ "${1:-}" = "./graith-demo" ]; then
	mkdir ./graith-demo
	printf 'thrawn\n' > ./graith-demo/replacement-sentinel
fi
EOF
	chmod +x "$fixture/bin/mv"
	if PATH="$fixture/bin:$PATH" run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored a replacement at the removal boundary"
	fi
	[ "$(cat "$fixture/config/graith-demo/replacement-sentinel")" = "thrawn" ] ||
		fail "teardown removed the replacement config directory"
	[ -d "$fixture/home/.graith-demo" ] || fail "teardown continued after the removal race"
	[ -d "$fixture/runtime/graith-demo" ] || fail "teardown removed runtime after the removal race"
}

assert_quarantine_swap_is_inode_bound() {
	new_fake_fixture "teardown-quarantine-race"
	write_owned_profile "$fixture" "$OWNER_A"
	mkdir -p "$fixture/bin"
	cat > "$fixture/bin/cat" <<'EOF'
#!/usr/bin/env bash
output="$(/bin/cat "$@")" || exit
printf '%s\n' "$output"
case "$PWD" in
	*.graith-removing-*)
		if [ ! -e "${GRAITH_DEMO_TEST_SWAP_ONCE:?}" ]; then
			: > "$GRAITH_DEMO_TEST_SWAP_ONCE"
			parent="${PWD%/*}"
			base="${PWD##*/}"
			/bin/mv "$PWD" "$parent/$base-owned"
			mkdir "$PWD"
			printf 'canny\n' > "$PWD/quarantine-replacement-sentinel"
		fi
		;;
esac
EOF
	chmod +x "$fixture/bin/cat"
	if GRAITH_DEMO_TEST_SWAP_ONCE="$fixture/swap-once" PATH="$fixture/bin:$PATH" \
		run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored a swapped quarantine target"
	fi
	quarantine="$fixture/config/.graith-demo.graith-removing-$OWNER_A"
	[ "$(/bin/cat "$quarantine/quarantine-replacement-sentinel")" = "canny" ] ||
		fail "teardown recursively deleted a swapped quarantine target"
	[ -d "$fixture/home/.graith-demo" ] || fail "teardown continued after the quarantine race"
	[ -d "$fixture/runtime/graith-demo" ] || fail "teardown removed runtime after the quarantine race"
}

build_real_gr() {
	[ -x "$REAL_GR" ] || (cd "$REPO_ROOT" && go build -o "$REAL_GR" ./cmd/graith)
}

assert_real_cli_runtime_recreation_and_rerun() {
	build_real_gr
	new_real_fixture "real-rerun"
	run_setup "$fixture" >/dev/null 2>&1 || fail "real-CLI first setup failed"
	first_owner="$(cat "$fixture/config/graith-demo/.graith-demo-owner")"
	if ! list_output="$(run_real_gr "$fixture" list -q 2>&1)"; then
		daemon_log="$(tail -40 "$fixture/home/.graith-demo/daemon.log" 2>/dev/null || true)"
		fail "real gr could not start after first setup: $list_output; daemon log: $daemon_log"
	fi
	if ! stop_output="$(run_real_gr "$fixture" daemon stop 2>&1)"; then
		fail "could not stop first real demo daemon: $stop_output"
	fi

	# Reproduce the real behavior that a fake alone missed: list recreates an
	# absent runtime directory without the harness marker.
	rm -rf "$fixture/runtime/graith-demo"
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "real gr list failed"
	[ -d "$fixture/runtime/graith-demo" ] || fail "real gr did not recreate the runtime directory"
	[ ! -e "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "real gr unexpectedly created a harness ownership marker"
	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop recreated real demo daemon"

	# Simulate the runtime directory being cleaned again at reboot. The rerun must
	# re-establish authorization before teardown's real gr calls and then finish.
	rm -rf "$fixture/runtime/graith-demo"
	: > "$fixture/gr.log"
	run_setup "$fixture" >/dev/null 2>&1 ||
		fail "real-CLI setup rerun failed after runtime recreation"
	grep -q ' list -q --json$' "$fixture/gr.log" || fail "rerun did not exercise real gr list"
	[ -f "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "real-CLI rerun left runtime state unowned"
	[ "$(cat "$fixture/config/graith-demo/.graith-demo-owner")" != "$first_owner" ] ||
		fail "real-CLI rerun did not rotate ownership"

	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop rerun daemon"
	run_teardown "$fixture" >/dev/null 2>&1 || fail "real-CLI final teardown failed"
}

assert_real_unowned_daemon_is_never_contacted() {
	build_real_gr
	new_real_fixture "real-unowned"
	write_unowned_config "$fixture"
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "could not start unowned real demo daemon"
	daemon_pid="$(cat "$fixture/runtime/graith-demo/graith.pid")"
	add_sentinels "$fixture"
	: > "$fixture/gr.log"

	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted an already-running unowned demo daemon"
	fi
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted an already-running unowned demo daemon"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] ||
		fail "harness contacted gr before refusing an unowned running daemon"
	[ "$(cat "$fixture/runtime/graith-demo/graith.pid")" = "$daemon_pid" ] ||
		fail "unowned daemon PID changed during refusal"
	kill -0 "$daemon_pid" 2>/dev/null || fail "unowned daemon stopped during refusal"

	# The real daemon still answers, proving the refusal did not stop or replace it.
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "unowned daemon was disturbed"
	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop unowned test daemon"
}

bash -n "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$0"
for target in config data runtime; do
	assert_refuses_setup_target "$target"
	assert_refuses_teardown_mismatch "$target"
done
assert_refuses_present_runtime_mismatch
assert_refuses_rebound_config
assert_refuses_untracked_runtime_fallback
assert_owned_teardown_is_idempotent
assert_refuses_on_active_list_failure
assert_refuses_before_any_purge
assert_refuses_after_purge_or_stop_failure
assert_replacement_at_remove_boundary_is_preserved
assert_quarantine_swap_is_inode_bound
assert_setup_reruns_after_runtime_cleanup
if [ "${GRAITH_DEMO_TEST_SKIP_REAL:-0}" -eq 1 ]; then
	echo "skipping real-CLI demo tests (GRAITH_DEMO_TEST_SKIP_REAL=1)"
else
	assert_real_cli_runtime_recreation_and_rerun
	assert_real_unowned_daemon_is_never_contacted
fi

echo "demo ownership tests passed"
