#!/usr/bin/env bash

set -euo pipefail

DEMO_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/graith-demo-test.XXXXXX")"
trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
	echo "FAIL: $*" >&2
	exit 1
}

new_fixture() {
	name="$1"
	fixture="$TEST_ROOT/$name"
	mkdir -p "$fixture/repo/demo" "$fixture/home" "$fixture/config" "$fixture/runtime"
	cp "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$fixture/repo/demo/"
	chmod +x "$fixture/repo/demo/setup.sh" "$fixture/repo/demo/teardown.sh"
	cat > "$fixture/repo/gr" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${GRAITH_DEMO_TEST_GR_LOG:?}"
case "$1" in
	list) exit "${GRAITH_DEMO_TEST_LIST_STATUS:-0}" ;;
	purge) exit "${GRAITH_DEMO_TEST_PURGE_STATUS:-0}" ;;
	daemon) exit "${GRAITH_DEMO_TEST_STOP_STATUS:-0}" ;;
esac
exit 0
EOF
	chmod +x "$fixture/repo/gr"
	: > "$fixture/gr.log"
}

run_setup() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" "$fixture/repo/demo/setup.sh"
}

run_teardown() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" "$fixture/repo/demo/teardown.sh"
}

assert_refuses_setup_target() {
	target="$1"
	new_fixture "setup-$target"
	fixture="$TEST_ROOT/setup-$target"
	case "$target" in
		config) sentinel="$fixture/config/graith-demo/sentinel" ;;
		data) sentinel="$fixture/home/.graith-demo/sentinel" ;;
		runtime) sentinel="$fixture/runtime/graith-demo/sentinel" ;;
	esac
	mkdir -p "$(dirname "$sentinel")"
	printf 'canny\n' > "$sentinel"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted pre-existing $target state"
	fi
	[ "$(cat "$sentinel")" = "canny" ] || fail "setup changed pre-existing $target state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for unowned $target state"
}

assert_refuses_teardown_mismatch() {
	new_fixture "teardown-mismatch"
	fixture="$TEST_ROOT/teardown-mismatch"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir" "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=braw — generated\n' > "$config_dir/config.toml"
	printf 'braw\n' > "$config_dir/.graith-demo-owner"
	printf 'thrawn\n' > "$data_dir/.graith-demo-owner"
	printf 'braw\n' > "$runtime_dir/.graith-demo-owner"
	printf 'dreich\n' > "$data_dir/sentinel"
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted mismatched ownership"
	fi
	[ "$(cat "$data_dir/sentinel")" = "dreich" ] || fail "teardown changed mismatched data"
	[ ! -s "$fixture/gr.log" ] || fail "teardown contacted gr for mismatched ownership"
}

assert_owned_teardown_is_idempotent() {
	new_fixture "teardown-owned"
	fixture="$TEST_ROOT/teardown-owned"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir" "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=bothy — generated\n' > "$config_dir/config.toml"
	for dir in "$config_dir" "$data_dir" "$runtime_dir"; do
		printf 'bothy\n' > "$dir/.graith-demo-owner"
	done
	run_teardown "$fixture" >/dev/null
	[ ! -e "$config_dir" ] && [ ! -e "$data_dir" ] && [ ! -e "$runtime_dir" ] ||
		fail "owned teardown left profile directories"
	run_teardown "$fixture" >/dev/null
}

assert_teardown_stops_on_gr_failure() {
	new_fixture "teardown-failure"
	fixture="$TEST_ROOT/teardown-failure"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir" "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=strath — generated\n' > "$config_dir/config.toml"
	for dir in "$config_dir" "$data_dir" "$runtime_dir"; do
		printf 'strath\n' > "$dir/.graith-demo-owner"
	done
	if GRAITH_DEMO_TEST_LIST_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored gr list failure"
	fi
	[ -d "$config_dir" ] && [ -d "$data_dir" ] && [ -d "$runtime_dir" ] ||
		fail "teardown removed state after gr failure"
}

# #1298 round-3: a rerun after only the ephemeral runtime dir is cleaned up (a
# reboot / logout) must still be accepted — the durable config/data markers prove
# ownership, and the runtime dir is reconstructible.
assert_setup_reruns_after_runtime_cleanup() {
	new_fixture "setup-rerun"
	fixture="$TEST_ROOT/setup-rerun"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"

	run_setup "$fixture" >/dev/null 2>&1 || fail "first setup failed"
	[ -f "$config_dir/config.toml" ] || fail "first setup wrote no config"
	[ -f "$runtime_dir/.graith-demo-owner" ] || fail "first setup wrote no runtime marker"
	first_owner="$(cat "$config_dir/.graith-demo-owner")"

	# Simulate the ephemeral runtime dir vanishing (reboot) while config/data
	# survive with their durable ownership markers.
	rm -rf "$runtime_dir"
	[ -f "$config_dir/.graith-demo-owner" ] || fail "config marker lost"
	[ -f "$data_dir/.graith-demo-owner" ] || fail "data marker lost"

	run_setup "$fixture" >/dev/null 2>&1 ||
		fail "setup refused an owned profile whose ephemeral runtime dir was cleaned up"
	[ -f "$runtime_dir/.graith-demo-owner" ] || fail "rerun did not reconstruct the runtime marker"
	# A fresh run re-establishes ownership, so the token rotates.
	[ "$(cat "$config_dir/.graith-demo-owner")" != "$first_owner" ] ||
		fail "rerun did not rotate the ownership token"
}

# #1298 round-3: durable config/data owned, but a *present* runtime target that
# is unowned/mismatched must still fail closed — the reconstructible exception is
# only for an absent runtime dir.
assert_refuses_setup_runtime_mismatch_with_durable_owner() {
	new_fixture "setup-runtime-mismatch"
	fixture="$TEST_ROOT/setup-runtime-mismatch"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir" "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=braw — generated\n' > "$config_dir/config.toml"
	printf 'braw\n' > "$config_dir/.graith-demo-owner"
	printf 'braw\n' > "$data_dir/.graith-demo-owner"
	# Runtime dir exists but belongs to someone else.
	printf 'thrawn\n' > "$runtime_dir/.graith-demo-owner"
	printf 'dreich\n' > "$runtime_dir/sentinel"

	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup adopted a present unowned runtime target despite durable ownership"
	fi
	[ "$(cat "$runtime_dir/sentinel")" = "dreich" ] || fail "setup changed the mismatched runtime state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for a mismatched runtime target"
}

bash -n "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$0"
for target in config data runtime; do
	assert_refuses_setup_target "$target"
done
assert_refuses_setup_runtime_mismatch_with_durable_owner
assert_setup_reruns_after_runtime_cleanup
assert_refuses_teardown_mismatch
assert_owned_teardown_is_idempotent
assert_teardown_stops_on_gr_failure

echo "demo ownership tests passed"
