#!/usr/bin/env bash

set -euo pipefail

DEMO_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_SOURCE/.." && pwd)"
# Keep the Unix-socket path comfortably below the macOS sockaddr_un limit even
# when the caller's TMPDIR is a deeply nested graith worktree path.
TEST_ROOT="$(mktemp -d "/tmp/graith-demo-test.XXXXXX")"
REAL_GR="$TEST_ROOT/gr-real"
REAL_FIXTURES="$TEST_ROOT/real-fixtures"
OWNER_A="baddcafebaddcafebaddcafebaddcafe"
OWNER_B="decafbaddecafbaddecafbaddecafbad"

fail() {
	echo "FAIL: $*" >&2
	exit 1
}

run_real_gr() {
	fixture="$1"
	shift
	(
		export HOME="$fixture/home"
		export XDG_CONFIG_HOME="$fixture/config"
		export XDG_RUNTIME_DIR="$fixture/runtime"
		export GRAITH_PROFILE=demo
		export GR_AGENT_MODE=0
		unset GRAITH_SESSION_ID GRAITH_SESSION_NAME GRAITH_AGENT_TYPE \
			GRAITH_WORKTREE_PATH GRAITH_REPO_PATH GRAITH_TOKEN 2>/dev/null || true
		"$REAL_GR" "$@"
	)
}

cleanup() {
	status=$?
	trap - EXIT INT TERM
	set +e
	if [ -f "$REAL_FIXTURES" ] && [ -x "$REAL_GR" ]; then
		while IFS= read -r fixture; do
			[ -z "$fixture" ] || run_real_gr "$fixture" daemon stop >/dev/null 2>&1
		done < "$REAL_FIXTURES"
	fi
	rm -rf "$TEST_ROOT"
	exit "$status"
}
trap cleanup EXIT INT TERM

new_fixture_base() {
	name="$1"
	fixture="$TEST_ROOT/$name"
	mkdir -p "$fixture/repo/demo" "$fixture/home" "$fixture/config" "$fixture/runtime"
	cp "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$fixture/repo/demo/"
	chmod +x "$fixture/repo/demo/setup.sh" "$fixture/repo/demo/teardown.sh"
	: > "$fixture/gr.log"
}

new_fake_fixture() {
	new_fixture_base "$1"
	cat > "$fixture/repo/gr" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${GRAITH_DEMO_TEST_GR_LOG:?}"
if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
	mkdir -p "$XDG_RUNTIME_DIR/graith-demo"
fi
case "${1:-}" in
	list)
		deleted=false
		for arg in "$@"; do
			[ "$arg" != "--deleted" ] || deleted=true
		done
		if $deleted; then
			[ "${GRAITH_DEMO_TEST_DELETED_LIST_STATUS:-0}" -eq 0 ] || exit "$GRAITH_DEMO_TEST_DELETED_LIST_STATUS"
			[ -z "${GRAITH_DEMO_TEST_DELETED_SESSIONS:-}" ] || printf '%s\n' "$GRAITH_DEMO_TEST_DELETED_SESSIONS"
		else
			[ "${GRAITH_DEMO_TEST_LIST_STATUS:-0}" -eq 0 ] || exit "$GRAITH_DEMO_TEST_LIST_STATUS"
			[ -z "${GRAITH_DEMO_TEST_ACTIVE_SESSIONS:-}" ] || printf '%s\n' "$GRAITH_DEMO_TEST_ACTIVE_SESSIONS"
		fi
		;;
	purge) exit "${GRAITH_DEMO_TEST_PURGE_STATUS:-0}" ;;
	daemon) exit "${GRAITH_DEMO_TEST_STOP_STATUS:-0}" ;;
esac
exit 0
EOF
	chmod +x "$fixture/repo/gr"
}

new_real_fixture() {
	new_fixture_base "$1"
	cat > "$fixture/repo/gr" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${GRAITH_DEMO_TEST_GR_LOG:?}"
case "${1:-}" in
	list|daemon) exec "${GRAITH_DEMO_REAL_GR:?}" "$@" ;;
	*) exit 0 ;;
esac
EOF
	chmod +x "$fixture/repo/gr"
	printf '%s\n' "$fixture" >> "$REAL_FIXTURES"
}

run_setup() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		GRAITH_DEMO_SRC_CONFIG="$fixture/missing-config.toml" "$fixture/repo/demo/setup.sh"
}

run_teardown() {
	fixture="$1"
	HOME="$fixture/home" XDG_CONFIG_HOME="$fixture/config" XDG_RUNTIME_DIR="$fixture/runtime" \
		GRAITH_DEMO_TEST_GR_LOG="$fixture/gr.log" GRAITH_DEMO_REAL_GR="$REAL_GR" \
		"$fixture/repo/demo/teardown.sh"
}

write_owned_profile() {
	fixture="$1" owner="$2" runtime="${3:-present}"
	config_dir="$fixture/config/graith-demo"
	data_dir="$fixture/home/.graith-demo"
	runtime_dir="$fixture/runtime/graith-demo"
	mkdir -p "$config_dir" "$data_dir"
	[ "$runtime" != "present" ] || mkdir -p "$runtime_dir"
	printf '# Generated by demo/setup.sh owner=%s — safe to delete. Isolated GRAITH_PROFILE=demo.\n' "$owner" > "$config_dir/config.toml"
	printf 'data_dir = "%s"\n' "$data_dir" >> "$config_dir/config.toml"
	printf '%s\n' "$owner" > "$config_dir/.graith-demo-owner"
	printf '%s\n' "$owner" > "$data_dir/.graith-demo-owner"
	[ "$runtime" != "present" ] || printf '%s\n' "$owner" > "$runtime_dir/.graith-demo-owner"
}

write_unowned_config() {
	fixture="$1"
	config_dir="$fixture/config/graith-demo"
	mkdir -p "$config_dir"
	printf '# pre-existing user config\ndata_dir = "%s"\n' "$fixture/home/.graith-demo" > "$config_dir/config.toml"
}

assert_sentinels() {
	fixture="$1"
	[ "$(cat "$fixture/config/graith-demo/config-sentinel")" = "canny" ] || fail "config sentinel changed"
	[ "$(cat "$fixture/home/.graith-demo/data-sentinel")" = "dreich" ] || fail "data sentinel changed"
	[ "$(cat "$fixture/runtime/graith-demo/runtime-sentinel")" = "thrawn" ] || fail "runtime sentinel changed"
}

add_sentinels() {
	fixture="$1"
	printf 'canny\n' > "$fixture/config/graith-demo/config-sentinel"
	printf 'dreich\n' > "$fixture/home/.graith-demo/data-sentinel"
	printf 'thrawn\n' > "$fixture/runtime/graith-demo/runtime-sentinel"
}

assert_refuses_setup_target() {
	target="$1"
	new_fake_fixture "setup-$target"
	case "$target" in
		config) sentinel="$fixture/config/graith-demo/sentinel" ;;
		data) sentinel="$fixture/home/.graith-demo/sentinel" ;;
		runtime) sentinel="$fixture/runtime/graith-demo/sentinel" ;;
	esac
	mkdir -p "$(dirname "$sentinel")"
	printf 'canny\n' > "$sentinel"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted pre-existing $target state"
	fi
	[ "$(cat "$sentinel")" = "canny" ] || fail "setup changed pre-existing $target state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for unowned $target state"
}

assert_refuses_teardown_mismatch() {
	target="$1"
	new_fake_fixture "teardown-$target-mismatch"
	write_owned_profile "$fixture" "$OWNER_A"
	add_sentinels "$fixture"
	case "$target" in
		config) printf '%s\n' "$OWNER_B" > "$fixture/config/graith-demo/.graith-demo-owner" ;;
		data) printf '%s\n' "$OWNER_B" > "$fixture/home/.graith-demo/.graith-demo-owner" ;;
		runtime) printf '%s\n' "$OWNER_B" > "$fixture/runtime/graith-demo/.graith-demo-owner" ;;
	esac
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted mismatched $target ownership"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] || fail "teardown contacted gr before refusing $target ownership"
}

assert_owned_teardown_is_idempotent() {
	new_fake_fixture "teardown-owned"
	write_owned_profile "$fixture" "$OWNER_A"
	run_teardown "$fixture" >/dev/null
	[ ! -e "$fixture/config/graith-demo" ] &&
		[ ! -e "$fixture/home/.graith-demo" ] &&
		[ ! -e "$fixture/runtime/graith-demo" ] ||
		fail "owned teardown left profile directories"
	run_teardown "$fixture" >/dev/null
}

assert_refuses_before_any_purge() {
	new_fake_fixture "teardown-list-failure"
	write_owned_profile "$fixture" "$OWNER_A"
	if GRAITH_DEMO_TEST_ACTIVE_SESSIONS="croft" \
		GRAITH_DEMO_TEST_DELETED_LIST_STATUS=1 run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown ignored deleted-session enumeration failure"
	fi
	grep -q '^list -q$' "$fixture/gr.log" || fail "teardown did not enumerate live sessions"
	grep -q '^list --deleted -q$' "$fixture/gr.log" || fail "teardown did not enumerate deleted sessions"
	if grep -q '^purge ' "$fixture/gr.log"; then
		fail "teardown purged before all refusal decisions completed"
	fi
	[ -d "$fixture/config/graith-demo" ] &&
		[ -d "$fixture/home/.graith-demo" ] &&
		[ -d "$fixture/runtime/graith-demo" ] ||
		fail "teardown removed state after pre-purge refusal"
}

assert_setup_reruns_after_runtime_cleanup() {
	new_fake_fixture "setup-rerun"
	run_setup "$fixture" >/dev/null 2>&1 || fail "first setup failed"
	first_owner="$(cat "$fixture/config/graith-demo/.graith-demo-owner")"
	rm -rf "$fixture/runtime/graith-demo"
	[ -f "$fixture/config/graith-demo/.graith-demo-owner" ] || fail "config ownership marker lost"
	[ -f "$fixture/home/.graith-demo/.graith-demo-owner" ] || fail "data ownership marker lost"
	run_setup "$fixture" >/dev/null 2>&1 ||
		fail "setup refused an owned profile after runtime cleanup"
	[ -f "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "rerun did not reconstruct runtime ownership"
	[ "$(cat "$fixture/config/graith-demo/.graith-demo-owner")" != "$first_owner" ] ||
		fail "rerun did not rotate the ownership token"
}

assert_refuses_present_runtime_mismatch() {
	new_fake_fixture "setup-runtime-mismatch"
	write_owned_profile "$fixture" "$OWNER_A"
	printf '%s\n' "$OWNER_B" > "$fixture/runtime/graith-demo/.graith-demo-owner"
	printf 'dreich\n' > "$fixture/runtime/graith-demo/sentinel"
	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup adopted a present mismatched runtime target"
	fi
	[ "$(cat "$fixture/runtime/graith-demo/sentinel")" = "dreich" ] ||
		fail "setup changed mismatched runtime state"
	[ ! -s "$fixture/gr.log" ] || fail "setup contacted gr for mismatched runtime state"
}

build_real_gr() {
	[ -x "$REAL_GR" ] || (cd "$REPO_ROOT" && go build -o "$REAL_GR" ./cmd/graith)
}

assert_real_cli_runtime_recreation_and_rerun() {
	build_real_gr
	new_real_fixture "real-rerun"
	run_setup "$fixture" >/dev/null 2>&1 || fail "real-CLI first setup failed"
	first_owner="$(cat "$fixture/config/graith-demo/.graith-demo-owner")"
	if ! list_output="$(run_real_gr "$fixture" list -q 2>&1)"; then
		daemon_log="$(tail -40 "$fixture/home/.graith-demo/daemon.log" 2>/dev/null || true)"
		fail "real gr could not start after first setup: $list_output; daemon log: $daemon_log"
	fi
	if ! stop_output="$(run_real_gr "$fixture" daemon stop 2>&1)"; then
		fail "could not stop first real demo daemon: $stop_output"
	fi

	# Reproduce the real behavior that a fake alone missed: list recreates an
	# absent runtime directory without the harness marker.
	rm -rf "$fixture/runtime/graith-demo"
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "real gr list failed"
	[ -d "$fixture/runtime/graith-demo" ] || fail "real gr did not recreate the runtime directory"
	[ ! -e "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "real gr unexpectedly created a harness ownership marker"
	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop recreated real demo daemon"

	# Simulate the runtime directory being cleaned again at reboot. The rerun must
	# re-establish authorization before teardown's real gr calls and then finish.
	rm -rf "$fixture/runtime/graith-demo"
	: > "$fixture/gr.log"
	run_setup "$fixture" >/dev/null 2>&1 ||
		fail "real-CLI setup rerun failed after runtime recreation"
	grep -q '^list -q$' "$fixture/gr.log" || fail "rerun did not exercise real gr list"
	[ -f "$fixture/runtime/graith-demo/.graith-demo-owner" ] ||
		fail "real-CLI rerun left runtime state unowned"
	[ "$(cat "$fixture/config/graith-demo/.graith-demo-owner")" != "$first_owner" ] ||
		fail "real-CLI rerun did not rotate ownership"

	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop rerun daemon"
	run_teardown "$fixture" >/dev/null 2>&1 || fail "real-CLI final teardown failed"
}

assert_real_unowned_daemon_is_never_contacted() {
	build_real_gr
	new_real_fixture "real-unowned"
	write_unowned_config "$fixture"
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "could not start unowned real demo daemon"
	add_sentinels "$fixture"
	: > "$fixture/gr.log"

	if run_setup "$fixture" >/dev/null 2>&1; then
		fail "setup accepted an already-running unowned demo daemon"
	fi
	if run_teardown "$fixture" >/dev/null 2>&1; then
		fail "teardown accepted an already-running unowned demo daemon"
	fi
	assert_sentinels "$fixture"
	[ ! -s "$fixture/gr.log" ] ||
		fail "harness contacted gr before refusing an unowned running daemon"

	# The real daemon still answers, proving the refusal did not stop or replace it.
	run_real_gr "$fixture" list -q >/dev/null 2>&1 || fail "unowned daemon was disturbed"
	run_real_gr "$fixture" daemon stop >/dev/null 2>&1 || fail "could not stop unowned test daemon"
}

bash -n "$DEMO_SOURCE/setup.sh" "$DEMO_SOURCE/teardown.sh" "$0"
for target in config data runtime; do
	assert_refuses_setup_target "$target"
	assert_refuses_teardown_mismatch "$target"
done
assert_refuses_present_runtime_mismatch
assert_owned_teardown_is_idempotent
assert_refuses_before_any_purge
assert_setup_reruns_after_runtime_cleanup
if [ "${GRAITH_DEMO_TEST_SKIP_REAL:-0}" -eq 1 ]; then
	echo "skipping real-CLI demo tests (GRAITH_DEMO_TEST_SKIP_REAL=1)"
else
	assert_real_cli_runtime_recreation_and_rerun
	assert_real_unowned_daemon_is_never_contacted
fi

echo "demo ownership tests passed"
