package protocol

// Cross-language protocol conformance (issue #1129).
//
// The wire protocol is defined twice: here in Go and, by hand, in Swift
// (`gui/shared/Sources/GraithProtocol/Messages.swift`). Nothing kept them in
// step, so drift was only ever caught by review. This file makes the Go side
// the single source of truth for the *shape* of the protocol: it enumerates
// every wire struct in messages.go and, via reflection, emits a language-neutral
// manifest of each type's JSON fields. That manifest is committed as a fixture
// (see manifest_test.go) and asserted against from both sides:
//
//   - Go (TestManifestUpToDate): regenerates the manifest and diffs it against
//     the committed fixture, so a change to messages.go that isn't regenerated
//     fails on the Go PR — which runs on *every* PR, closing the gap that
//     gui/ Swift CI is paths-filtered and would miss a Go-only change.
//   - Swift (ManifestConformanceTests): decodes the same fixture and verifies
//     that every type the manifest marks `required` has a Swift decoder that
//     accepts a synthesized instance — so when Go adds a required message the
//     Swift suite goes red until Messages.swift catches up.
//
// The manifest also records, per type, whether Swift is expected to model it
// (`required`), is a known-but-unfilled gap (`planned`), or will never need it
// (`na`, e.g. hook-CLI/daemon-internal or local-only messages). That turns the
// current 119-vs-32 divergence into an explicit, reviewable list rather than
// silent drift.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// SwiftExpectation classifies whether the Swift client is expected to model a
// given Go wire type.
type SwiftExpectation string

const (
	// SwiftRequired: the Swift app models (or must model) this type. The
	// conformance test fails if Swift cannot decode a synthesized instance.
	SwiftRequired SwiftExpectation = "required"
	// SwiftPlanned: a client-relevant type Swift does not model yet — an
	// acknowledged gap. Not enforced against Swift, but recorded so the gap is
	// visible and reviewable.
	SwiftPlanned SwiftExpectation = "planned"
	// SwiftNA: a type a GUI/remote client never needs — hook-CLI↔daemon
	// internals, MCP proxy transport, or local-only (doctor/diagnostics/upgrade)
	// messages. Not modelled by Swift, and never expected to be.
	SwiftNA SwiftExpectation = "na"
)

// FieldType is a language-neutral description of a wire field's type. Kind is
// one of: string, int, float, bool, raw (a `json.RawMessage` opaque blob), map,
// array, object. array carries Elem; object carries Ref (the name of another
// manifest type).
//
// Known fidelity limits (none exercised by messages.go today, guarded so they
// can't silently appear): map loses its key/value types (kind "map" only); a
// fixed-length array loses its length (kind "array"); and describeFields rejects
// embedded/anonymous struct fields outright rather than mis-modelling
// encoding/json's field promotion. A plain `[]byte` is reported as "string"
// (encoding/json base64-encodes it), distinct from `json.RawMessage` ("raw").
type FieldType struct {
	Kind string     `json:"kind"`
	Elem *FieldType `json:"elem,omitempty"`
	Ref  string     `json:"ref,omitempty"`
}

// ManifestField is one JSON field of a wire type.
type ManifestField struct {
	// Name is the JSON key (the `json:"…"` tag), not the Go field name.
	Name string    `json:"name"`
	Type FieldType `json:"type"`
	// Optional is true when the field is a pointer or carries `omitempty` — i.e.
	// it may be absent from the wire form. Swift models these as Optional.
	Optional bool `json:"optional"`
}

// ManifestType is one wire struct: its Go name, its Swift expectation, and its
// fields in declaration order.
type ManifestType struct {
	Name      string           `json:"name"`
	Swift     SwiftExpectation `json:"swift"`
	SwiftType string           `json:"swift_type,omitempty"` // Swift type that satisfies it (required only)
	Fields    []ManifestField  `json:"fields"`
}

// Manifest is the committed, cross-language description of the wire protocol.
type Manifest struct {
	ProtocolVersion string `json:"protocol_version"`
	// Note is a human-oriented pointer back to the generator, embedded so the
	// committed fixture is self-documenting.
	Note  string         `json:"note"`
	Types []ManifestType `json:"types"`
}

// manifestNote is embedded in the generated fixture so a reader who stumbles
// onto it knows not to hand-edit it.
const manifestNote = "GENERATED by internal/protocol. Do not edit by hand. " +
	"Run: go test ./internal/protocol -run TestManifestUpToDate -update"

// registeredTypes is one zero value per wire struct in messages.go. It is the
// input to reflection-based manifest generation. TestManifestRegistryComplete
// (in manifest_test.go) parses messages.go and fails if any exported struct is
// missing here (or a stale entry lingers), so this list cannot silently fall
// behind the source.
var registeredTypes = []any{
	Envelope{},
	HandshakeMsg{},
	CreateMsg{},
	ForkMsg{},
	MigrateMsg{},
	AttachMsg{},
	DeleteMsg{},
	ListMsg{},
	RestoreMsg{},
	DeleteResultMsg{},
	RestoreResultMsg{},
	GCMsg{},
	GCOrphanInfo{},
	GCResultMsg{},
	RenameMsg{},
	UpdateMsg{},
	StarMsg{},
	UnstarMsg{},
	SetStatusMsg{},
	StatusSetMsg{},
	StopMsg{},
	TypeMsg{},
	InterruptMsg{},
	ResumeMsg{},
	RestartMsg{},
	UpgradeMsg{},
	ResizeMsg{},
	LogsMsg{},
	WaitMsg{},
	WaitMatchedMsg{},
	MsgPubMsg{},
	MsgSubMsg{},
	MsgInboxMsg{},
	MsgAckMsg{},
	MsgTopicsMsg{},
	MsgConversationMsg{},
	ConversationMessage{},
	MsgConversationListMsg{},
	JailedCommentInfo{},
	MsgJailListMsg{},
	MsgJailListResponse{},
	MsgJailShowMsg{},
	MsgJailShowResponse{},
	MsgJailReleaseMsg{},
	MsgJailReleaseResponse{},
	NotifyMsg{},
	NotifyResponse{},
	StatusReportMsg{},
	HandshakeOkMsg{},
	HandshakeErrMsg{},
	SessionListMsg{},
	SessionInfo{},
	PRInfo{},
	CIInfo{},
	TokenInfo{},
	IncludedRepoInfo{},
	DetachedMsg{},
	ErrorMsg{},
	ScreenPreviewMsg{},
	ScreenPreviewResponseMsg{},
	ApprovalRequestMsg{},
	ApprovalInfo{},
	ApprovalNotificationMsg{},
	ApprovalRespondMsg{},
	ApprovalDecisionMsg{},
	ScreenSnapshotMsg{},
	ScreenSnapshotResponseMsg{},
	MCPConnectMsg{},
	MCPConnectOkMsg{},
	MCPListMsg{},
	MCPConnectionInfo{},
	MCPServerStatus{},
	MCPListResponse{},
	MCPRestartMsg{},
	MCPRestartResponse{},
	MCPLogsMsg{},
	MCPLogFile{},
	MCPLogsResponse{},
	StatusRequestMsg{},
	DiagnosticsMsg{},
	SessionDiagnostic{},
	TriggerDiagnostic{},
	ScrollbackDiagnostic{},
	MessagesDiagnostic{},
	FleetSummary{},
	StatusResponseMsg{},
	ScenarioStartMsg{},
	ScenarioSessionInput{},
	ScenarioStopMsg{},
	ScenarioDeleteMsg{},
	ScenarioStatusMsg{},
	ScenarioListMsg{},
	ScenarioRecord{},
	ScenarioSessionInfo{},
	ScenarioStatusResponse{},
	ScenarioListResponse{},
	TriggerListMsg{},
	TriggerStatusMsg{},
	TriggerRunMsg{},
	TriggerPauseMsg{},
	TriggerRecord{},
	TriggerListResponse{},
	TriggerStatusResponse{},
	ScenarioResumeMsg{},
	ScenarioTaskDoneMsg{},
	ScenarioAddMsg{},
	PairRequestMsg{},
	PairResponseMsg{},
	PairApproveMsg{},
	PairListMsg{},
	PairListResponseMsg{},
	PairPending{},
	PairedDeviceInfo{},
	PairRevokeMsg{},
	AuthChallengeMsg{},
	AuthProofMsg{},
	ApprovalSubscribeMsg{},
	RepoListMsg{},
	RepoListResponseMsg{},
	RepoEntry{},
	StoreListMsg{},
	StoreEntryInfo{},
	StoreListResponseMsg{},
	StoreGetMsg{},
	StoreGetResponseMsg{},
}

// swiftAnnotation pairs a Swift expectation with the Swift type that satisfies
// it (for `required` types; empty otherwise). Several Go structs deliberately
// map to one consolidated Swift type (SessionScopeMsg, SessionIDMsg, EmptyMsg) —
// the Swift app models the shared shape once. For those, the conformance test
// only guarantees the required (non-optional) wire fields decode; a Go-only
// optional field (e.g. DeleteMsg.purge) is not required to be settable in Swift.
type swiftAnnotation struct {
	exp   SwiftExpectation
	swift string
}

// swiftAnnotations classifies EVERY registered type. A registered type missing
// here is a hard error in TestManifestRegistryComplete (fail closed), so adding
// a wire struct forces a deliberate Swift-expectation decision — the same
// discipline as the remoteMessagePolicy table for the auth matrix. New types
// default to nothing (a compile-and-test failure) rather than silently
// "planned", so the choice of required/planned/na is always reviewed.
var swiftAnnotations = map[string]swiftAnnotation{
	// Transport envelope — Swift models it as ControlEnvelope in Control.swift
	// (not Messages.swift), with custom raw-payload handling. It wraps every
	// control message, so a rename of type/payload/token would break the wire:
	// the Swift conformance test registers a dedicated decodeControl-based probe.
	"Envelope": {SwiftRequired, "ControlEnvelope"},

	// Handshake.
	"HandshakeMsg":    {SwiftRequired, "HandshakeMsg"},
	"HandshakeOkMsg":  {SwiftRequired, "HandshakeOkMsg"},
	"HandshakeErrMsg": {SwiftRequired, "HandshakeErrMsg"},

	// Lifecycle / control (client -> daemon).
	"CreateMsg":    {SwiftRequired, "CreateMsg"},
	"ForkMsg":      {SwiftRequired, "ForkMsg"},
	"MigrateMsg":   {SwiftRequired, "MigrateMsg"},
	"AttachMsg":    {SwiftRequired, "AttachMsg"},
	"RenameMsg":    {SwiftRequired, "RenameMsg"},
	"SetStatusMsg": {SwiftRequired, "SetStatusMsg"},
	"TypeMsg":      {SwiftRequired, "TypeMsg"},
	"ResizeMsg":    {SwiftRequired, "ResizeMsg"},
	"LogsMsg":      {SwiftRequired, "LogsMsg"},

	// stop/delete/restart/restore share Swift's SessionScopeMsg (session_id +
	// children + exclude_root + purge). DeleteMsg's `purge` is now settable in
	// Swift (the `gr purge` GUI path, #1148); RestoreMsg carries only the
	// session_id + children subset SessionScopeMsg already models.
	"StopMsg":    {SwiftRequired, "SessionScopeMsg"},
	"DeleteMsg":  {SwiftRequired, "SessionScopeMsg"},
	"RestartMsg": {SwiftRequired, "SessionScopeMsg"},
	"RestoreMsg": {SwiftRequired, "SessionScopeMsg"},

	// Bare {session_id} requests share Swift's SessionIDMsg.
	"InterruptMsg":      {SwiftRequired, "SessionIDMsg"},
	"ResumeMsg":         {SwiftRequired, "SessionIDMsg"},
	"StarMsg":           {SwiftRequired, "SessionIDMsg"},
	"UnstarMsg":         {SwiftRequired, "SessionIDMsg"},
	"StatusRequestMsg":  {SwiftRequired, "SessionIDMsg"},
	"ScreenPreviewMsg":  {SwiftRequired, "SessionIDMsg"},
	"ScreenSnapshotMsg": {SwiftRequired, "SessionIDMsg"},

	// No-payload requests share Swift's EmptyMsg. ListMsg's optional `deleted`
	// is Go-only for now (EmptyMsg satisfies the default `list`).
	"ListMsg":         {SwiftRequired, "EmptyMsg"},
	"MCPListMsg":      {SwiftRequired, "EmptyMsg"},
	"ScenarioListMsg": {SwiftRequired, "EmptyMsg"},
	"TriggerListMsg":  {SwiftRequired, "EmptyMsg"},
	"PairListMsg":     {SwiftRequired, "EmptyMsg"},

	// Session model (daemon -> client).
	"SessionListMsg":   {SwiftRequired, "SessionListMsg"},
	"SessionInfo":      {SwiftRequired, "SessionInfo"},
	"PRInfo":           {SwiftRequired, "PRInfo"},
	"CIInfo":           {SwiftRequired, "CIInfo"},
	"IncludedRepoInfo": {SwiftRequired, "IncludedRepoInfo"},
	"DetachedMsg":      {SwiftRequired, "DetachedMsg"},
	"ErrorMsg":         {SwiftRequired, "ErrorMsg"},

	// Screen peek.
	"ScreenPreviewResponseMsg":  {SwiftRequired, "ScreenPreviewResponseMsg"},
	"ScreenSnapshotResponseMsg": {SwiftRequired, "ScreenSnapshotResponseMsg"},

	// Approvals (the client-facing subset).
	"ApprovalInfo":            {SwiftRequired, "ApprovalInfo"},
	"ApprovalNotificationMsg": {SwiftRequired, "ApprovalNotificationMsg"},
	"ApprovalRespondMsg":      {SwiftRequired, "ApprovalRespondMsg"},
	"ApprovalSubscribeMsg":    {SwiftRequired, "ApprovalSubscribeMsg"},

	// Pairing + proof-of-possession.
	"PairRequestMsg":      {SwiftRequired, "PairRequestMsg"},
	"PairResponseMsg":     {SwiftRequired, "PairResponseMsg"},
	"PairApproveMsg":      {SwiftRequired, "PairApproveMsg"},
	"PairListResponseMsg": {SwiftRequired, "PairListResponseMsg"},
	"PairPending":         {SwiftRequired, "PairPending"},
	"PairedDeviceInfo":    {SwiftRequired, "PairedDeviceInfo"},
	"PairRevokeMsg":       {SwiftRequired, "PairRevokeMsg"},
	"AuthChallengeMsg":    {SwiftRequired, "AuthChallengeMsg"},
	"AuthProofMsg":        {SwiftRequired, "AuthProofMsg"},

	// Remote-create repo picker.
	"RepoListMsg":         {SwiftRequired, "RepoListMsg"},
	"RepoListResponseMsg": {SwiftRequired, "RepoListResponseMsg"},
	"RepoEntry":           {SwiftRequired, "RepoEntry"},

	// Document store browser (#902).
	"StoreListMsg":         {SwiftRequired, "StoreListMsg"},
	"StoreEntryInfo":       {SwiftRequired, "StoreEntryInfo"},
	"StoreListResponseMsg": {SwiftRequired, "StoreListResponseMsg"},
	"StoreGetMsg":          {SwiftRequired, "StoreGetMsg"},
	"StoreGetResponseMsg":  {SwiftRequired, "StoreGetResponseMsg"},

	// --- Planned: client-relevant, not modelled in Swift yet (known gaps). ---
	"DeleteResultMsg":        {SwiftPlanned, ""},
	"RestoreResultMsg":       {SwiftPlanned, ""},
	"UpdateMsg":              {SwiftPlanned, ""},
	"StatusSetMsg":           {SwiftPlanned, ""},
	"WaitMsg":                {SwiftPlanned, ""},
	"WaitMatchedMsg":         {SwiftPlanned, ""},
	"MsgPubMsg":              {SwiftRequired, "MsgPubMsg"},
	"MsgSubMsg":              {SwiftPlanned, ""},
	"MsgInboxMsg":            {SwiftPlanned, ""},
	"MsgAckMsg":              {SwiftRequired, "MsgAckMsg"},
	"MsgTopicsMsg":           {SwiftPlanned, ""},
	"MsgConversationMsg":     {SwiftRequired, "MsgConversationMsg"},
	"ConversationMessage":    {SwiftRequired, "ConversationMessage"},
	"MsgConversationListMsg": {SwiftRequired, "MsgConversationListMsg"},
	"JailedCommentInfo":      {SwiftPlanned, ""},
	"MsgJailListMsg":         {SwiftPlanned, ""},
	"MsgJailListResponse":    {SwiftPlanned, ""},
	"MsgJailShowMsg":         {SwiftPlanned, ""},
	"MsgJailShowResponse":    {SwiftPlanned, ""},
	"MsgJailReleaseMsg":      {SwiftPlanned, ""},
	"MsgJailReleaseResponse": {SwiftPlanned, ""},
	"NotifyMsg":              {SwiftPlanned, ""},
	"NotifyResponse":         {SwiftPlanned, ""},
	"TokenInfo":              {SwiftPlanned, ""},
	"FleetSummary":           {SwiftPlanned, ""},
	"StatusResponseMsg":      {SwiftPlanned, ""},
	"MCPConnectionInfo":      {SwiftPlanned, ""},
	"MCPServerStatus":        {SwiftPlanned, ""},
	"MCPListResponse":        {SwiftPlanned, ""},
	"MCPRestartMsg":          {SwiftPlanned, ""},
	"MCPRestartResponse":     {SwiftPlanned, ""},
	"MCPLogsMsg":             {SwiftPlanned, ""},
	"MCPLogFile":             {SwiftPlanned, ""},
	"MCPLogsResponse":        {SwiftPlanned, ""},
	// Scenario reads + lifecycle wired into the GUI (#903). The `{name}` requests
	// (stop/resume/delete) consolidate onto Swift's ScenarioNameMsg, like the
	// SessionIDMsg pattern. start/task-done/add stay planned — they are
	// orchestrator-session-scoped, not human-client operations.
	"ScenarioStopMsg":      {SwiftRequired, "ScenarioNameMsg"},
	"ScenarioResumeMsg":    {SwiftRequired, "ScenarioNameMsg"},
	"ScenarioDeleteMsg":    {SwiftRequired, "ScenarioNameMsg"},
	"ScenarioRecord":       {SwiftRequired, "ScenarioRecord"},
	"ScenarioSessionInfo":  {SwiftRequired, "ScenarioSessionInfo"},
	"ScenarioListResponse": {SwiftRequired, "ScenarioListResponse"},

	"ScenarioStartMsg":       {SwiftPlanned, ""},
	"ScenarioSessionInput":   {SwiftPlanned, ""},
	"ScenarioStatusMsg":      {SwiftPlanned, ""},
	"ScenarioStatusResponse": {SwiftPlanned, ""},
	"ScenarioTaskDoneMsg":    {SwiftPlanned, ""},
	"ScenarioAddMsg":         {SwiftPlanned, ""},
	"TriggerStatusMsg":       {SwiftPlanned, ""},
	"TriggerRunMsg":          {SwiftPlanned, ""},
	"TriggerPauseMsg":        {SwiftPlanned, ""},
	"TriggerRecord":          {SwiftPlanned, ""},
	"TriggerListResponse":    {SwiftPlanned, ""},
	"TriggerStatusResponse":  {SwiftPlanned, ""},

	// --- Not applicable: a GUI/remote client never decodes these. ---
	"StatusReportMsg":      {SwiftNA, ""}, // hook CLI -> daemon
	"ApprovalRequestMsg":   {SwiftNA, ""}, // hook CLI -> daemon
	"ApprovalDecisionMsg":  {SwiftNA, ""}, // daemon -> hook CLI
	"MCPConnectMsg":        {SwiftNA, ""}, // MCP proxy transport
	"MCPConnectOkMsg":      {SwiftNA, ""}, // MCP proxy transport
	"UpgradeMsg":           {SwiftNA, ""}, // local-only
	"GCMsg":                {SwiftNA, ""}, // local-only (doctor)
	"GCOrphanInfo":         {SwiftNA, ""}, // local-only (doctor)
	"GCResultMsg":          {SwiftNA, ""}, // local-only (doctor)
	"DiagnosticsMsg":       {SwiftNA, ""}, // local-only
	"SessionDiagnostic":    {SwiftNA, ""}, // local-only
	"TriggerDiagnostic":    {SwiftNA, ""}, // local-only (doctor)
	"ScrollbackDiagnostic": {SwiftNA, ""}, // local-only
	"MessagesDiagnostic":   {SwiftNA, ""}, // local-only
}

// rawMessageType is encoding/json.RawMessage, treated as an opaque JSON blob.
var rawMessageType = reflect.TypeOf(json.RawMessage(nil))

// BuildManifest reflects over registeredTypes and produces the manifest,
// annotated with each type's Swift expectation. Types are sorted by name for a
// stable, diff-friendly fixture; fields keep declaration order.
func BuildManifest() (Manifest, error) {
	types := make([]ManifestType, 0, len(registeredTypes))
	seen := make(map[string]bool, len(registeredTypes))

	for _, v := range registeredTypes {
		rt := reflect.TypeOf(v)
		if rt.Kind() != reflect.Struct {
			return Manifest{}, fmt.Errorf("registered type %s is not a struct", rt.Name())
		}

		if seen[rt.Name()] {
			return Manifest{}, fmt.Errorf("type %s is registered more than once in registeredTypes", rt.Name())
		}

		seen[rt.Name()] = true

		ann, ok := swiftAnnotations[rt.Name()]
		if !ok {
			return Manifest{}, fmt.Errorf("type %s has no swiftAnnotations entry — classify it (required/planned/na)", rt.Name())
		}

		fields, err := describeFields(rt)
		if err != nil {
			return Manifest{}, fmt.Errorf("describe %s: %w", rt.Name(), err)
		}

		types = append(types, ManifestType{
			Name:      rt.Name(),
			Swift:     ann.exp,
			SwiftType: ann.swift,
			Fields:    fields,
		})
	}

	sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })

	return Manifest{
		ProtocolVersion: Version,
		Note:            manifestNote,
		Types:           types,
	}, nil
}

// describeFields walks a struct's exported, JSON-serialized fields in
// declaration order. It always returns a non-nil slice so a fieldless struct
// (e.g. the no-payload request messages) marshals to `[]`, not `null` — cleaner
// to decode cross-language.
func describeFields(rt reflect.Type) ([]ManifestField, error) {
	fields := make([]ManifestField, 0, rt.NumField())
	for i := 0; i < rt.NumField(); i++ {
		f := rt.Field(i)
		if f.PkgPath != "" {
			continue // unexported
		}

		if f.Anonymous {
			// encoding/json promotes an untagged embedded struct's fields inline,
			// which describeFields does not model. Reject rather than emit a
			// misleading nested object. None exist today; this keeps it honest.
			return nil, fmt.Errorf("embedded/anonymous field %s is not supported by the manifest generator", f.Name)
		}

		name, omitempty, skip := jsonKey(f)
		if skip {
			continue
		}

		optional := omitempty

		ft := f.Type
		if ft.Kind() == reflect.Pointer {
			optional = true
			ft = ft.Elem()
		}

		desc, err := describeType(ft)
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", f.Name, err)
		}

		fields = append(fields, ManifestField{
			Name:     name,
			Type:     desc,
			Optional: optional,
		})
	}

	return fields, nil
}

// jsonKey resolves a field's wire name and whether it carries omitempty. skip is
// true for `json:"-"`.
func jsonKey(f reflect.StructField) (name string, omitempty, skip bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, true
	}

	parts := strings.Split(tag, ",")

	name = parts[0]
	if name == "" {
		name = f.Name // Go default: the field name
	}

	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			omitempty = true
		}
	}

	return name, omitempty, false
}

// describeType maps a (non-pointer) Go type to a language-neutral FieldType.
func describeType(t reflect.Type) (FieldType, error) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}

	if t == rawMessageType {
		return FieldType{Kind: "raw"}, nil
	}

	switch t.Kind() {
	case reflect.String:
		return FieldType{Kind: "string"}, nil
	case reflect.Bool:
		return FieldType{Kind: "bool"}, nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return FieldType{Kind: "int"}, nil
	case reflect.Float32, reflect.Float64:
		return FieldType{Kind: "float"}, nil
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			// A plain []byte (that isn't json.RawMessage, handled above) is
			// base64-encoded as a JSON string by encoding/json.
			return FieldType{Kind: "string"}, nil
		}

		elem, err := describeType(t.Elem())
		if err != nil {
			return FieldType{}, err
		}

		return FieldType{Kind: "array", Elem: &elem}, nil
	case reflect.Array:
		elem, err := describeType(t.Elem())
		if err != nil {
			return FieldType{}, err
		}

		return FieldType{Kind: "array", Elem: &elem}, nil
	case reflect.Map:
		return FieldType{Kind: "map"}, nil
	case reflect.Struct:
		return FieldType{Kind: "object", Ref: t.Name()}, nil
	default:
		return FieldType{}, fmt.Errorf("unsupported kind %s", t.Kind())
	}
}

// MarshalManifest renders the manifest as stable, indented JSON with a trailing
// newline and HTML escaping disabled (so `<`/`>`/`&` in any future field survive
// verbatim). This is the exact byte form committed as the fixture.
func MarshalManifest(m Manifest) ([]byte, error) {
	var buf bytes.Buffer

	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")

	if err := enc.Encode(m); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
